In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pd.set_option("display.max_columns",None)
pd.set_option("display.max_rows",None)
df=pd.read_csv("application_data.csv")

In [ ]:
#knowing the data
print("top 5 rows of data:\n\n",df.head(5))

top 5 rows of data:

    SK_ID_CURR  TARGET NAME_CONTRACT_TYPE CODE_GENDER FLAG_OWN_CAR  \
0      100002       1         Cash loans           M            N
1      100003       0         Cash loans           F            N
2      100004       0    Revolving loans           M            Y
3      100006       0         Cash loans           F            N
4      100007       0         Cash loans           M            N

  FLAG_OWN_REALTY  CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  AMT_ANNUITY  \
0               Y             0          202500.0    406597.5      24700.5
1               N             0          270000.0   1293502.5      35698.5
2               Y             0           67500.0    135000.0       6750.0
3               Y             0          135000.0    312682.5      29686.5
4               Y             0          121500.0    513000.0      21865.5

   AMT_GOODS_PRICE NAME_TYPE_SUITE NAME_INCOME_TYPE  \
0         351000.0   Unaccompanied          Working
1        1129500.0          Family    State servant
2         135000.0   Unaccompanied          Working
3         297000.0   Unaccompanied          Working
4         513000.0   Unaccompanied          Working

             NAME_EDUCATION_TYPE    NAME_FAMILY_STATUS  NAME_HOUSING_TYPE  \
0  Secondary / secondary special  Single / not married  House / apartment
1               Higher education               Married  House / apartment
2  Secondary / secondary special  Single / not married  House / apartment
3  Secondary / secondary special        Civil marriage  House / apartment
4  Secondary / secondary special  Single / not married  House / apartment

   REGION_POPULATION_RELATIVE  DAYS_BIRTH  DAYS_EMPLOYED  DAYS_REGISTRATION  \
0                    0.018801       -9461           -637            -3648.0
1                    0.003541      -16765          -1188            -1186.0
2                    0.010032      -19046           -225            -4260.0
3                    0.008019      -19005          -3039            -9833.0
4                    0.028663      -19932          -3038            -4311.0

   DAYS_ID_PUBLISH  OWN_CAR_AGE  FLAG_MOBIL  FLAG_EMP_PHONE  FLAG_WORK_PHONE  \
0            -2120          NaN           1               1                0
1             -291          NaN           1               1                0
2            -2531         26.0           1               1                1
3            -2437          NaN           1               1                0
4            -3458          NaN           1               1                0

   FLAG_CONT_MOBILE  FLAG_PHONE  FLAG_EMAIL OCCUPATION_TYPE  CNT_FAM_MEMBERS  \
0                 1           1           0        Laborers              1.0
1                 1           1           0      Core staff              2.0
2                 1           1           0        Laborers              1.0
3                 1           0           0        Laborers              2.0
4                 1           0           0      Core staff              1.0

   REGION_RATING_CLIENT  REGION_RATING_CLIENT_W_CITY  \
0                     2                            2
1                     1                            1
2                     2                            2
3                     2                            2
4                     2                            2

  WEEKDAY_APPR_PROCESS_START  HOUR_APPR_PROCESS_START  \
0                  WEDNESDAY                       10
1                     MONDAY                       11
2                     MONDAY                        9
3                  WEDNESDAY                       17
4                   THURSDAY                       11

   REG_REGION_NOT_LIVE_REGION  REG_REGION_NOT_WORK_REGION  \
0                           0                           0
1                           0                           0
2                           0                           0
3                           0                           0
4                           0                           0

   LIVE_REGION_NOT_WORK_REGION  REG_CITY_NOT_LIVE_CITY  \
0                            0                       0
1                            0                       0
2                            0                       0
3                            0                       0
4                            0                       0

   REG_CITY_NOT_WORK_CITY  LIVE_CITY_NOT_WORK_CITY       ORGANIZATION_TYPE  \
0                       0                        0  Business Entity Type 3
1                       0                        0                  School
2                       0                        0              Government
3                       0                        0  Business Entity Type 3
4                       1                        1                Religion

   EXT_SOURCE_1  EXT_SOURCE_2  EXT_SOURCE_3  APARTMENTS_AVG  BASEMENTAREA_AVG  \
0      0.083037      0.262949      0.139376          0.0247            0.0369
1      0.311267      0.622246           NaN          0.0959            0.0529
2           NaN      0.555912      0.729567             NaN               NaN
3           NaN      0.650442           NaN             NaN               NaN
4           NaN      0.322738           NaN             NaN               NaN

   YEARS_BEGINEXPLUATATION_AVG  YEARS_BUILD_AVG  COMMONAREA_AVG  \
0                       0.9722           0.6192          0.0143
1                       0.9851           0.7960          0.0605
2                          NaN              NaN             NaN
3                          NaN              NaN             NaN
4                          NaN              NaN             NaN

   ELEVATORS_AVG  ENTRANCES_AVG  FLOORSMAX_AVG  FLOORSMIN_AVG  LANDAREA_AVG  \
0           0.00         0.0690         0.0833         0.1250        0.0369
1           0.08         0.0345         0.2917         0.3333        0.0130
2            NaN            NaN            NaN            NaN           NaN
3            NaN            NaN            NaN            NaN           NaN
4            NaN            NaN            NaN            NaN           NaN

   LIVINGAPARTMENTS_AVG  LIVINGAREA_AVG  NONLIVINGAPARTMENTS_AVG  \
0                0.0202          0.0190                   0.0000
1                0.0773          0.0549                   0.0039
2                   NaN             NaN                      NaN
3                   NaN             NaN                      NaN
4                   NaN             NaN                      NaN

   NONLIVINGAREA_AVG  APARTMENTS_MODE  BASEMENTAREA_MODE  \
0             0.0000           0.0252             0.0383
1             0.0098           0.0924             0.0538
2                NaN              NaN                NaN
3                NaN              NaN                NaN
4                NaN              NaN                NaN

   YEARS_BEGINEXPLUATATION_MODE  YEARS_BUILD_MODE  COMMONAREA_MODE  \
0                        0.9722            0.6341           0.0144
1                        0.9851            0.8040           0.0497
2                           NaN               NaN              NaN
3                           NaN               NaN              NaN
4                           NaN               NaN              NaN

   ELEVATORS_MODE  ENTRANCES_MODE  FLOORSMAX_MODE  FLOORSMIN_MODE  \
0          0.0000          0.0690          0.0833          0.1250
1          0.0806          0.0345          0.2917          0.3333
2             NaN             NaN             NaN             NaN
3             NaN             NaN             NaN             NaN
4             NaN             NaN             NaN             NaN

   LANDAREA_MODE  LIVINGAPARTMENTS_MODE  LIVINGAREA_MODE  \
0         0.0377                  0.022           0.0198
1         0.0128                  0.079           0.0554
2            NaN                    NaN              NaN
3            NaN                    NaN              NaN
4            NaN                    NaN              NaN

   NONLIVINGAPARTMENTS_MODE  NONLIVINGAREA_MODE  APARTMENTS_MEDI  \
0                       0.0                 0.0           0.0250
1                       0.0                 0.0           0.0968
2                       NaN                 NaN              NaN
3                       NaN                 NaN              NaN
4                       NaN                 NaN              NaN

   BASEMENTAREA_MEDI  YEARS_BEGINEXPLUATATION_MEDI  YEARS_BUILD_MEDI  \
0             0.0369                        0.9722            0.6243
1             0.0529                        0.9851            0.7987
2                NaN                           NaN               NaN
3                NaN                           NaN               NaN
4                NaN                           NaN               NaN

   COMMONAREA_MEDI  ELEVATORS_MEDI  ENTRANCES_MEDI  FLOORSMAX_MEDI  \
0           0.0144            0.00          0.0690          0.0833
1           0.0608            0.08          0.0345          0.2917
2              NaN             NaN             NaN             NaN
3              NaN             NaN             NaN             NaN
4              NaN             NaN             NaN             NaN

   FLOORSMIN_MEDI  LANDAREA_MEDI  LIVINGAPARTMENTS_MEDI  LIVINGAREA_MEDI  \
0          0.1250         0.0375                 0.0205           0.0193
1          0.3333         0.0132                 0.0787           0.0558
2             NaN            NaN                    NaN              NaN
3             NaN            NaN                    NaN              NaN
4             NaN            NaN                    NaN              NaN

   NONLIVINGAPARTMENTS_MEDI  NONLIVINGAREA_MEDI FONDKAPREMONT_MODE  \
0                    0.0000                0.00   reg oper account
1                    0.0039                0.01   reg oper account
2                       NaN                 NaN                NaN
3                       NaN                 NaN                NaN
4                       NaN                 NaN                NaN

   HOUSETYPE_MODE  TOTALAREA_MODE WALLSMATERIAL_MODE EMERGENCYSTATE_MODE  \
0  block of flats          0.0149       Stone, brick                  No
1  block of flats          0.0714              Block                  No
2             NaN             NaN                NaN                 NaN
3             NaN             NaN                NaN                 NaN
4             NaN             NaN                NaN                 NaN

   OBS_30_CNT_SOCIAL_CIRCLE  DEF_30_CNT_SOCIAL_CIRCLE  \
0                       2.0                       2.0
1                       1.0                       0.0
2                       0.0                       0.0
3                       2.0                       0.0
4                       0.0                       0.0

   OBS_60_CNT_SOCIAL_CIRCLE  DEF_60_CNT_SOCIAL_CIRCLE  DAYS_LAST_PHONE_CHANGE  \
0                       2.0                       2.0                 -1134.0
1                       1.0                       0.0                  -828.0
2                       0.0                       0.0                  -815.0
3                       2.0                       0.0                  -617.0
4                       0.0                       0.0                 -1106.0

   FLAG_DOCUMENT_2  FLAG_DOCUMENT_3  FLAG_DOCUMENT_4  FLAG_DOCUMENT_5  \
0                0                1                0                0
1                0                1                0                0
2                0                0                0                0
3                0                1                0                0
4                0                0                0                0

   FLAG_DOCUMENT_6  FLAG_DOCUMENT_7  FLAG_DOCUMENT_8  FLAG_DOCUMENT_9  \
0                0                0                0                0
1                0                0                0                0
2                0                0                0                0
3                0                0                0                0
4                0                0                1                0

   FLAG_DOCUMENT_10  FLAG_DOCUMENT_11  FLAG_DOCUMENT_12  FLAG_DOCUMENT_13  \
0                 0                 0                 0                 0
1                 0                 0                 0                 0
2                 0                 0                 0                 0
3                 0                 0                 0                 0
4                 0                 0                 0                 0

   FLAG_DOCUMENT_14  FLAG_DOCUMENT_15  FLAG_DOCUMENT_16  FLAG_DOCUMENT_17  \
0                 0                 0                 0                 0
1                 0                 0                 0                 0
2                 0                 0                 0                 0
3                 0                 0                 0                 0
4                 0                 0                 0                 0

   FLAG_DOCUMENT_18  FLAG_DOCUMENT_19  FLAG_DOCUMENT_20  FLAG_DOCUMENT_21  \
0                 0                 0                 0                 0
1                 0                 0                 0                 0
2                 0                 0                 0                 0
3                 0                 0                 0                 0
4                 0                 0                 0                 0

   AMT_REQ_CREDIT_BUREAU_HOUR  AMT_REQ_CREDIT_BUREAU_DAY  \
0                         0.0                        0.0
1                         0.0                        0.0
2                         0.0                        0.0
3                         NaN                        NaN
4                         0.0                        0.0

   AMT_REQ_CREDIT_BUREAU_WEEK  AMT_REQ_CREDIT_BUREAU_MON  \
0                         0.0                        0.0
1                         0.0                        0.0
2                         0.0                        0.0
3                         NaN                        NaN
4                         0.0                        0.0

   AMT_REQ_CREDIT_BUREAU_QRT  AMT_REQ_CREDIT_BUREAU_YEAR
0                        0.0                         1.0
1                        0.0                         0.0
2                        0.0                         0.0
3                        NaN                         NaN
4                        0.0                         0.0

In [ ]:
print("Getting information about column\n\n", df.dtypes)

Getting information about column

 SK_ID_CURR                        int64
TARGET                            int64
NAME_CONTRACT_TYPE               object
CODE_GENDER                      object
FLAG_OWN_CAR                     object
FLAG_OWN_REALTY                  object
CNT_CHILDREN                      int64
AMT_INCOME_TOTAL                float64
AMT_CREDIT                      float64
AMT_ANNUITY                     float64
AMT_GOODS_PRICE                 float64
NAME_TYPE_SUITE                  object
NAME_INCOME_TYPE                 object
NAME_EDUCATION_TYPE              object
NAME_FAMILY_STATUS               object
NAME_HOUSING_TYPE                object
REGION_POPULATION_RELATIVE      float64
DAYS_BIRTH                        int64
DAYS_EMPLOYED                     int64
DAYS_REGISTRATION               float64
DAYS_ID_PUBLISH                   int64
OWN_CAR_AGE                     float64
FLAG_MOBIL                        int64
FLAG_EMP_PHONE                    int64
FLAG_WORK_PHONE                   int64
FLAG_CONT_MOBILE                  int64
FLAG_PHONE                        int64
FLAG_EMAIL                        int64
OCCUPATION_TYPE                  object
CNT_FAM_MEMBERS                 float64
REGION_RATING_CLIENT              int64
REGION_RATING_CLIENT_W_CITY       int64
WEEKDAY_APPR_PROCESS_START       object
HOUR_APPR_PROCESS_START           int64
REG_REGION_NOT_LIVE_REGION        int64
REG_REGION_NOT_WORK_REGION        int64
LIVE_REGION_NOT_WORK_REGION       int64
REG_CITY_NOT_LIVE_CITY            int64
REG_CITY_NOT_WORK_CITY            int64
LIVE_CITY_NOT_WORK_CITY           int64
ORGANIZATION_TYPE                object
EXT_SOURCE_1                    float64
EXT_SOURCE_2                    float64
EXT_SOURCE_3                    float64
APARTMENTS_AVG                  float64
BASEMENTAREA_AVG                float64
YEARS_BEGINEXPLUATATION_AVG     float64
YEARS_BUILD_AVG                 float64
COMMONAREA_AVG                  float64
ELEVATORS_AVG                   float64
ENTRANCES_AVG                   float64
FLOORSMAX_AVG                   float64
FLOORSMIN_AVG                   float64
LANDAREA_AVG                    float64
LIVINGAPARTMENTS_AVG            float64
LIVINGAREA_AVG                  float64
NONLIVINGAPARTMENTS_AVG         float64
NONLIVINGAREA_AVG               float64
APARTMENTS_MODE                 float64
BASEMENTAREA_MODE               float64
YEARS_BEGINEXPLUATATION_MODE    float64
YEARS_BUILD_MODE                float64
COMMONAREA_MODE                 float64
ELEVATORS_MODE                  float64
ENTRANCES_MODE                  float64
FLOORSMAX_MODE                  float64
FLOORSMIN_MODE                  float64
LANDAREA_MODE                   float64
LIVINGAPARTMENTS_MODE           float64
LIVINGAREA_MODE                 float64
NONLIVINGAPARTMENTS_MODE        float64
NONLIVINGAREA_MODE              float64
APARTMENTS_MEDI                 float64
BASEMENTAREA_MEDI               float64
YEARS_BEGINEXPLUATATION_MEDI    float64
YEARS_BUILD_MEDI                float64
COMMONAREA_MEDI                 float64
ELEVATORS_MEDI                  float64
ENTRANCES_MEDI                  float64
FLOORSMAX_MEDI                  float64
FLOORSMIN_MEDI                  float64
LANDAREA_MEDI                   float64
LIVINGAPARTMENTS_MEDI           float64
LIVINGAREA_MEDI                 float64
NONLIVINGAPARTMENTS_MEDI        float64
NONLIVINGAREA_MEDI              float64
FONDKAPREMONT_MODE               object
HOUSETYPE_MODE                   object
TOTALAREA_MODE                  float64
WALLSMATERIAL_MODE               object
EMERGENCYSTATE_MODE              object
OBS_30_CNT_SOCIAL_CIRCLE        float64
DEF_30_CNT_SOCIAL_CIRCLE        float64
OBS_60_CNT_SOCIAL_CIRCLE        float64
DEF_60_CNT_SOCIAL_CIRCLE        float64
DAYS_LAST_PHONE_CHANGE          float64
FLAG_DOCUMENT_2                   int64
FLAG_DOCUMENT_3                   int64
FLAG_DOCUMENT_4                   int64
FLAG_DOCUMENT_5                   int64
FLAG_DOCUMENT_6                   int64
FLAG_DOCUMENT_7                   int64
FLAG_DOCUMENT_8                   int64
FLAG_DOCUMENT_9                   int64
FLAG_DOCUMENT_10                  int64
FLAG_DOCUMENT_11                  int64
FLAG_DOCUMENT_12                  int64
FLAG_DOCUMENT_13                  int64
FLAG_DOCUMENT_14                  int64
FLAG_DOCUMENT_15                  int64
FLAG_DOCUMENT_16                  int64
FLAG_DOCUMENT_17                  int64
FLAG_DOCUMENT_18                  int64
FLAG_DOCUMENT_19                  int64
FLAG_DOCUMENT_20                  int64
FLAG_DOCUMENT_21                  int64
AMT_REQ_CREDIT_BUREAU_HOUR      float64
AMT_REQ_CREDIT_BUREAU_DAY       float64
AMT_REQ_CREDIT_BUREAU_WEEK      float64
AMT_REQ_CREDIT_BUREAU_MON       float64
AMT_REQ_CREDIT_BUREAU_QRT       float64
AMT_REQ_CREDIT_BUREAU_YEAR      float64
dtype: object

In [ ]:
print("Getting name of all columns: \n\n",df.columns)

Getting name of all columns:

 Index(['SK_ID_CURR', 'TARGET', 'NAME_CONTRACT_TYPE', 'CODE_GENDER',
       'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL',
       'AMT_CREDIT', 'AMT_ANNUITY',
       ...
       'FLAG_DOCUMENT_18', 'FLAG_DOCUMENT_19', 'FLAG_DOCUMENT_20',
       'FLAG_DOCUMENT_21', 'AMT_REQ_CREDIT_BUREAU_HOUR',
       'AMT_REQ_CREDIT_BUREAU_DAY', 'AMT_REQ_CREDIT_BUREAU_WEEK',
       'AMT_REQ_CREDIT_BUREAU_MON', 'AMT_REQ_CREDIT_BUREAU_QRT',
       'AMT_REQ_CREDIT_BUREAU_YEAR'],
      dtype='object', length=122)

In [ ]:
print(f"no. of row:{df.shape[0]}\n no. of columns: {df.shape[1]}")

no. of row:307511
 no. of columns: 122

In [ ]:
#checking for nan values
(df.isna().sum()/len(df)*100).sort_values(axis=0)

SK_ID_CURR                       0.000000
HOUR_APPR_PROCESS_START          0.000000
REG_REGION_NOT_WORK_REGION       0.000000
LIVE_REGION_NOT_WORK_REGION      0.000000
REG_CITY_NOT_LIVE_CITY           0.000000
REG_CITY_NOT_WORK_CITY           0.000000
LIVE_CITY_NOT_WORK_CITY          0.000000
ORGANIZATION_TYPE                0.000000
FLAG_DOCUMENT_21                 0.000000
FLAG_DOCUMENT_20                 0.000000
FLAG_DOCUMENT_19                 0.000000
FLAG_DOCUMENT_18                 0.000000
FLAG_DOCUMENT_17                 0.000000
FLAG_DOCUMENT_16                 0.000000
FLAG_DOCUMENT_15                 0.000000
FLAG_DOCUMENT_14                 0.000000
FLAG_DOCUMENT_13                 0.000000
FLAG_DOCUMENT_12                 0.000000
FLAG_DOCUMENT_11                 0.000000
FLAG_DOCUMENT_10                 0.000000
FLAG_DOCUMENT_9                  0.000000
FLAG_DOCUMENT_8                  0.000000
FLAG_DOCUMENT_7                  0.000000
FLAG_DOCUMENT_6                  0.000000
FLAG_DOCUMENT_5                  0.000000
FLAG_DOCUMENT_4                  0.000000
FLAG_DOCUMENT_3                  0.000000
FLAG_DOCUMENT_2                  0.000000
WEEKDAY_APPR_PROCESS_START       0.000000
REGION_RATING_CLIENT_W_CITY      0.000000
REG_REGION_NOT_LIVE_REGION       0.000000
NAME_HOUSING_TYPE                0.000000
CNT_CHILDREN                     0.000000
NAME_INCOME_TYPE                 0.000000
NAME_EDUCATION_TYPE              0.000000
NAME_FAMILY_STATUS               0.000000
REGION_RATING_CLIENT             0.000000
REGION_POPULATION_RELATIVE       0.000000
DAYS_BIRTH                       0.000000
DAYS_EMPLOYED                    0.000000
DAYS_REGISTRATION                0.000000
DAYS_ID_PUBLISH                  0.000000
AMT_INCOME_TOTAL                 0.000000
FLAG_OWN_REALTY                  0.000000
CODE_GENDER                      0.000000
NAME_CONTRACT_TYPE               0.000000
FLAG_MOBIL                       0.000000
FLAG_EMP_PHONE                   0.000000
FLAG_WORK_PHONE                  0.000000
FLAG_CONT_MOBILE                 0.000000
FLAG_PHONE                       0.000000
TARGET                           0.000000
FLAG_EMAIL                       0.000000
FLAG_OWN_CAR                     0.000000
AMT_CREDIT                       0.000000
DAYS_LAST_PHONE_CHANGE           0.000325
CNT_FAM_MEMBERS                  0.000650
AMT_ANNUITY                      0.003902
AMT_GOODS_PRICE                  0.090403
EXT_SOURCE_2                     0.214626
DEF_30_CNT_SOCIAL_CIRCLE         0.332021
DEF_60_CNT_SOCIAL_CIRCLE         0.332021
OBS_60_CNT_SOCIAL_CIRCLE         0.332021
OBS_30_CNT_SOCIAL_CIRCLE         0.332021
NAME_TYPE_SUITE                  0.420148
AMT_REQ_CREDIT_BUREAU_HOUR      13.501631
AMT_REQ_CREDIT_BUREAU_DAY       13.501631
AMT_REQ_CREDIT_BUREAU_MON       13.501631
AMT_REQ_CREDIT_BUREAU_WEEK      13.501631
AMT_REQ_CREDIT_BUREAU_YEAR      13.501631
AMT_REQ_CREDIT_BUREAU_QRT       13.501631
EXT_SOURCE_3                    19.825307
OCCUPATION_TYPE                 31.345545
EMERGENCYSTATE_MODE             47.398304
TOTALAREA_MODE                  48.268517
YEARS_BEGINEXPLUATATION_MODE    48.781019
YEARS_BEGINEXPLUATATION_AVG     48.781019
YEARS_BEGINEXPLUATATION_MEDI    48.781019
FLOORSMAX_AVG                   49.760822
FLOORSMAX_MEDI                  49.760822
FLOORSMAX_MODE                  49.760822
HOUSETYPE_MODE                  50.176091
LIVINGAREA_AVG                  50.193326
LIVINGAREA_MODE                 50.193326
LIVINGAREA_MEDI                 50.193326
ENTRANCES_AVG                   50.348768
ENTRANCES_MODE                  50.348768
ENTRANCES_MEDI                  50.348768
APARTMENTS_MEDI                 50.749729
APARTMENTS_AVG                  50.749729
APARTMENTS_MODE                 50.749729
WALLSMATERIAL_MODE              50.840783
ELEVATORS_MEDI                  53.295980
ELEVATORS_AVG                   53.295980
ELEVATORS_MODE                  53.295980
NONLIVINGAREA_MODE              55.179164
NONLIVINGAREA_AVG               55.179164
NONLIVINGAREA_MEDI              55.179164
EXT_SOURCE_1                    56.381073
BASEMENTAREA_MODE               58.515956
BASEMENTAREA_AVG                58.515956
BASEMENTAREA_MEDI               58.515956
LANDAREA_MEDI                   59.376738
LANDAREA_AVG                    59.376738
LANDAREA_MODE                   59.376738
OWN_CAR_AGE                     65.990810
YEARS_BUILD_MODE                66.497784
YEARS_BUILD_AVG                 66.497784
YEARS_BUILD_MEDI                66.497784
FLOORSMIN_AVG                   67.848630
FLOORSMIN_MODE                  67.848630
FLOORSMIN_MEDI                  67.848630
LIVINGAPARTMENTS_AVG            68.354953
LIVINGAPARTMENTS_MODE           68.354953
LIVINGAPARTMENTS_MEDI           68.354953
FONDKAPREMONT_MODE              68.386172
NONLIVINGAPARTMENTS_AVG         69.432963
NONLIVINGAPARTMENTS_MEDI        69.432963
NONLIVINGAPARTMENTS_MODE        69.432963
COMMONAREA_MODE                 69.872297
COMMONAREA_AVG                  69.872297
COMMONAREA_MEDI                 69.872297
dtype: float64

In [ ]:
print("columns with more than 50% of Nan values \n\n")
na_val=((df.isna().sum()/len(df))*100).sort_values()>50
print("count of columns:",na_val[na_val.values==True].count(),"\n\n ")
print(na_val[na_val.values==True])

columns with more than 50% of Nan values


count of columns: 41


HOUSETYPE_MODE              True
LIVINGAREA_AVG              True
LIVINGAREA_MODE             True
LIVINGAREA_MEDI             True
ENTRANCES_AVG               True
ENTRANCES_MODE              True
ENTRANCES_MEDI              True
APARTMENTS_MEDI             True
APARTMENTS_AVG              True
APARTMENTS_MODE             True
WALLSMATERIAL_MODE          True
ELEVATORS_MEDI              True
ELEVATORS_AVG               True
ELEVATORS_MODE              True
NONLIVINGAREA_MODE          True
NONLIVINGAREA_AVG           True
NONLIVINGAREA_MEDI          True
EXT_SOURCE_1                True
BASEMENTAREA_MODE           True
BASEMENTAREA_AVG            True
BASEMENTAREA_MEDI           True
LANDAREA_MEDI               True
LANDAREA_AVG                True
LANDAREA_MODE               True
OWN_CAR_AGE                 True
YEARS_BUILD_MODE            True
YEARS_BUILD_AVG             True
YEARS_BUILD_MEDI            True
FLOORSMIN_AVG               True
FLOORSMIN_MODE              True
FLOORSMIN_MEDI              True
LIVINGAPARTMENTS_AVG        True
LIVINGAPARTMENTS_MODE       True
LIVINGAPARTMENTS_MEDI       True
FONDKAPREMONT_MODE          True
NONLIVINGAPARTMENTS_AVG     True
NONLIVINGAPARTMENTS_MEDI    True
NONLIVINGAPARTMENTS_MODE    True
COMMONAREA_MODE             True
COMMONAREA_AVG              True
COMMONAREA_MEDI             True
dtype: bool

In [ ]:
df.shape

(307511, 122)

In [ ]:
df.describe().transpose()
#	Target variable 
#1 - client with payment difficulties:he/she had late payment more than X days on at least one of the first Y installments of the loan in our sample,
#0 - all other cases

,count,mean,std,min,25%,50%,75%,max
SK_ID_CURR,307511.0,278180.518577,102790.175348,1.000020e+05,189145.500000,278202.000000,367142.500000,4.562550e+05
TARGET,307511.0,0.080729,0.272419,0.000000e+00,0.000000,0.000000,0.000000,1.000000e+00
CNT_CHILDREN,307511.0,0.417052,0.722121,0.000000e+00,0.000000,0.000000,1.000000,1.900000e+01
AMT_INCOME_TOTAL,307511.0,168797.919297,237123.146279,2.565000e+04,112500.000000,147150.000000,202500.000000,1.170000e+08
AMT_CREDIT,307511.0,599025.999706,402490.776996,4.500000e+04,270000.000000,513531.000000,808650.000000,4.050000e+06
AMT_ANNUITY,307499.0,27108.573909,14493.737315,1.615500e+03,16524.000000,24903.000000,34596.000000,2.580255e+05
AMT_GOODS_PRICE,307233.0,538396.207429,369446.460540,4.050000e+04,238500.000000,450000.000000,679500.000000,4.050000e+06
REGION_POPULATION_RELATIVE,307511.0,0.020868,0.013831,2.900000e-04,0.010006,0.018850,0.028663,7.250800e-02
DAYS_BIRTH,307511.0,-16036.995067,4363.988632,-2.522900e+04,-19682.000000,-15750.000000,-12413.000000,-7.489000e+03
DAYS_EMPLOYED,307511.0,63815.045904,141275.766519,-1.791200e+04,-2760.000000,-1213.000000,-289.000000,3.652430e+05
DAYS_REGISTRATION,307511.0,-4986.120328,3522.886321,-2.467200e+04,-7479.500000,-4504.000000,-2010.000000,0.000000e+00
DAYS_ID_PUBLISH,307511.0,-2994.202373,1509.450419,-7.197000e+03,-4299.000000,-3254.000000,-1720.000000,0.000000e+00
OWN_CAR_AGE,104582.0,12.061091,11.944812,0.000000e+00,5.000000,9.000000,15.000000,9.100000e+01
FLAG_MOBIL,307511.0,0.999997,0.001803,0.000000e+00,1.000000,1.000000,1.000000,1.000000e+00
FLAG_EMP_PHONE,307511.0,0.819889,0.384280,0.000000e+00,1.000000,1.000000,1.000000,1.000000e+00
FLAG_WORK_PHONE,307511.0,0.199368,0.399526,0.000000e+00,0.000000,0.000000,0.000000,1.000000e+00
FLAG_CONT_MOBILE,307511.0,0.998133,0.043164,0.000000e+00,1.000000,1.000000,1.000000,1.000000e+00
FLAG_PHONE,307511.0,0.281066,0.449521,0.000000e+00,0.000000,0.000000,1.000000,1.000000e+00
FLAG_EMAIL,307511.0,0.056720,0.231307,0.000000e+00,0.000000,0.000000,0.000000,1.000000e+00
CNT_FAM_MEMBERS,307509.0,2.152665,0.910682,1.000000e+00,2.000000,2.000000,3.000000,2.000000e+01
REGION_RATING_CLIENT,307511.0,2.052463,0.509034,1.000000e+00,2.000000,2.000000,2.000000,3.000000e+00
REGION_RATING_CLIENT_W_CITY,307511.0,2.031521,0.502737,1.000000e+00,2.000000,2.000000,2.000000,3.000000e+00
HOUR_APPR_PROCESS_START,307511.0,12.063419,3.265832,0.000000e+00,10.000000,12.000000,14.000000,2.300000e+01
REG_REGION_NOT_LIVE_REGION,307511.0,0.015144,0.122126,0.000000e+00,0.000000,0.000000,0.000000,1.000000e+00
REG_REGION_NOT_WORK_REGION,307511.0,0.050769,0.219526,0.000000e+00,0.000000,0.000000,0.000000,1.000000e+00
LIVE_REGION_NOT_WORK_REGION,307511.0,0.040659,0.197499,0.000000e+00,0.000000,0.000000,0.000000,1.000000e+00
REG_CITY_NOT_LIVE_CITY,307511.0,0.078173,0.268444,0.000000e+00,0.000000,0.000000,0.000000,1.000000e+00
REG_CITY_NOT_WORK_CITY,307511.0,0.230454,0.421124,0.000000e+00,0.000000,0.000000,0.000000,1.000000e+00
LIVE_CITY_NOT_WORK_CITY,307511.0,0.179555,0.383817,0.000000e+00,0.000000,0.000000,0.000000,1.000000e+00
EXT_SOURCE_1,134133.0,0.502130,0.211062,1.456813e-02,0.334007,0.505998,0.675053,9.626928e-01
EXT_SOURCE_2,306851.0,0.514393,0.191060,8.173617e-08,0.392457,0.565961,0.663617,8.549997e-01
EXT_SOURCE_3,246546.0,0.510853,0.194844,5.272652e-04,0.370650,0.535276,0.669057,8.960095e-01
APARTMENTS_AVG,151450.0,0.117440,0.108240,0.000000e+00,0.057700,0.087600,0.148500,1.000000e+00
BASEMENTAREA_AVG,127568.0,0.088442,0.082438,0.000000e+00,0.044200,0.076300,0.112200,1.000000e+00
YEARS_BEGINEXPLUATATION_AVG,157504.0,0.977735,0.059223,0.000000e+00,0.976700,0.981600,0.986600,1.000000e+00
YEARS_BUILD_AVG,103023.0,0.752471,0.113280,0.000000e+00,0.687200,0.755200,0.823200,1.000000e+00
COMMONAREA_AVG,92646.0,0.044621,0.076036,0.000000e+00,0.007800,0.021100,0.051500,1.000000e+00
ELEVATORS_AVG,143620.0,0.078942,0.134576,0.000000e+00,0.000000,0.000000,0.120000,1.000000e+00
ENTRANCES_AVG,152683.0,0.149725,0.100049,0.000000e+00,0.069000,0.137900,0.206900,1.000000e+00
FLOORSMAX_AVG,154491.0,0.226282,0.144641,0.000000e+00,0.166700,0.166700,0.333300,1.000000e+00
FLOORSMIN_AVG,98869.0,0.231894,0.161380,0.000000e+00,0.083300,0.208300,0.375000,1.000000e+00
LANDAREA_AVG,124921.0,0.066333,0.081184,0.000000e+00,0.018700,0.048100,0.085600,1.000000e+00
LIVINGAPARTMENTS_AVG,97312.0,0.100775,0.092576,0.000000e+00,0.050400,0.075600,0.121000,1.000000e+00
LIVINGAREA_AVG,153161.0,0.107399,0.110565,0.000000e+00,0.045300,0.074500,0.129900,1.000000e+00
NONLIVINGAPARTMENTS_AVG,93997.0,0.008809,0.047732,0.000000e+00,0.000000,0.000000,0.003900,1.000000e+00
NONLIVINGAREA_AVG,137829.0,0.028358,0.069523,0.000000e+00,0.000000,0.003600,0.027700,1.000000e+00
APARTMENTS_MODE,151450.0,0.114231,0.107936,0.000000e+00,0.052500,0.084000,0.143900,1.000000e+00
BASEMENTAREA_MODE,127568.0,0.087543,0.084307,0.000000e+00,0.040700,0.074600,0.112400,1.000000e+00
YEARS_BEGINEXPLUATATION_MODE,157504.0,0.977065,0.064575,0.000000e+00,0.976700,0.981600,0.986600,1.000000e+00
YEARS_BUILD_MODE,103023.0,0.759637,0.110111,0.000000e+00,0.699400,0.764800,0.823600,1.000000e+00
COMMONAREA_MODE,92646.0,0.042553,0.074445,0.000000e+00,0.007200,0.019000,0.049000,1.000000e+00
ELEVATORS_MODE,143620.0,0.074490,0.132256,0.000000e+00,0.000000,0.000000,0.120800,1.000000e+00
ENTRANCES_MODE,152683.0,0.145193,0.100977,0.000000e+00,0.069000,0.137900,0.206900,1.000000e+00
FLOORSMAX_MODE,154491.0,0.222315,0.143709,0.000000e+00,0.166700,0.166700,0.333300,1.000000e+00
FLOORSMIN_MODE,98869.0,0.228058,0.161160,0.000000e+00,0.083300,0.208300,0.375000,1.000000e+00
LANDAREA_MODE,124921.0,0.064958,0.081750,0.000000e+00,0.016600,0.045800,0.084100,1.000000e+00
LIVINGAPARTMENTS_MODE,97312.0,0.105645,0.097880,0.000000e+00,0.054200,0.077100,0.131300,1.000000e+00
LIVINGAREA_MODE,153161.0,0.105975,0.111845,0.000000e+00,0.042700,0.073100,0.125200,1.000000e+00
NONLIVINGAPARTMENTS_MODE,93997.0,0.008076,0.046276,0.000000e+00,0.000000,0.000000,0.003900,1.000000e+00
NONLIVINGAREA_MODE,137829.0,0.027022,0.070254,0.000000e+00,0.000000,0.001100,0.023100,1.000000e+00
APARTMENTS_MEDI,151450.0,0.117850,0.109076,0.000000e+00,0.058300,0.086400,0.148900,1.000000e+00
BASEMENTAREA_MEDI,127568.0,0.087955,0.082179,0.000000e+00,0.043700,0.075800,0.111600,1.000000e+00
YEARS_BEGINEXPLUATATION_MEDI,157504.0,0.977752,0.059897,0.000000e+00,0.976700,0.981600,0.986600,1.000000e+00
YEARS_BUILD_MEDI,103023.0,0.755746,0.112066,0.000000e+00,0.691400,0.758500,0.825600,1.000000e+00
COMMONAREA_MEDI,92646.0,0.044595,0.076144,0.000000e+00,0.007900,0.020800,0.051300,1.000000e+00
ELEVATORS_MEDI,143620.0,0.078078,0.134467,0.000000e+00,0.000000,0.000000,0.120000,1.000000e+00
ENTRANCES_MEDI,152683.0,0.149213,0.100368,0.000000e+00,0.069000,0.137900,0.206900,1.000000e+00
FLOORSMAX_MEDI,154491.0,0.225897,0.145067,0.000000e+00,0.166700,0.166700,0.333300,1.000000e+00
FLOORSMIN_MEDI,98869.0,0.231625,0.161934,0.000000e+00,0.083300,0.208300,0.375000,1.000000e+00
LANDAREA_MEDI,124921.0,0.067169,0.082167,0.000000e+00,0.018700,0.048700,0.086800,1.000000e+00
LIVINGAPARTMENTS_MEDI,97312.0,0.101954,0.093642,0.000000e+00,0.051300,0.076100,0.123100,1.000000e+00
LIVINGAREA_MEDI,153161.0,0.108607,0.112260,0.000000e+00,0.045700,0.074900,0.130300,1.000000e+00
NONLIVINGAPARTMENTS_MEDI,93997.0,0.008651,0.047415,0.000000e+00,0.000000,0.000000,0.003900,1.000000e+00
NONLIVINGAREA_MEDI,137829.0,0.028236,0.070166,0.000000e+00,0.000000,0.003100,0.026600,1.000000e+00
TOTALAREA_MODE,159080.0,0.102547,0.107462,0.000000e+00,0.041200,0.068800,0.127600,1.000000e+00
OBS_30_CNT_SOCIAL_CIRCLE,306490.0,1.422245,2.400989,0.000000e+00,0.000000,0.000000,2.000000,3.480000e+02
DEF_30_CNT_SOCIAL_CIRCLE,306490.0,0.143421,0.446698,0.000000e+00,0.000000,0.000000,0.000000,3.400000e+01
OBS_60_CNT_SOCIAL_CIRCLE,306490.0,1.405292,2.379803,0.000000e+00,0.000000,0.000000,2.000000,3.440000e+02
DEF_60_CNT_SOCIAL_CIRCLE,306490.0,0.100049,0.362291,0.000000e+00,0.000000,0.000000,0.000000,2.400000e+01
DAYS_LAST_PHONE_CHANGE,307510.0,-962.858788,826.808487,-4.292000e+03,-1570.000000,-757.000000,-274.000000,0.000000e+00
FLAG_DOCUMENT_2,307511.0,0.000042,0.006502,0.000000e+00,0.000000,0.000000,0.000000,1.000000e+00
FLAG_DOCUMENT_3,307511.0,0.710023,0.453752,0.000000e+00,0.000000,1.000000,1.000000,1.000000e+00
FLAG_DOCUMENT_4,307511.0,0.000081,0.009016,0.000000e+00,0.000000,0.000000,0.000000,1.000000e+00
FLAG_DOCUMENT_5,307511.0,0.015115,0.122010,0.000000e+00,0.000000,0.000000,0.000000,1.000000e+00
FLAG_DOCUMENT_6,307511.0,0.088055,0.283376,0.000000e+00,0.000000,0.000000,0.000000,1.000000e+00
FLAG_DOCUMENT_7,307511.0,0.000192,0.013850,0.000000e+00,0.000000,0.000000,0.000000,1.000000e+00
FLAG_DOCUMENT_8,307511.0,0.081376,0.273412,0.000000e+00,0.000000,0.000000,0.000000,1.000000e+00
FLAG_DOCUMENT_9,307511.0,0.003896,0.062295,0.000000e+00,0.000000,0.000000,0.000000,1.000000e+00
FLAG_DOCUMENT_10,307511.0,0.000023,0.004771,0.000000e+00,0.000000,0.000000,0.000000,1.000000e+00
FLAG_DOCUMENT_11,307511.0,0.003912,0.062424,0.000000e+00,0.000000,0.000000,0.000000,1.000000e+00
FLAG_DOCUMENT_12,307511.0,0.000007,0.002550,0.000000e+00,0.000000,0.000000,0.000000,1.000000e+00
FLAG_DOCUMENT_13,307511.0,0.003525,0.059268,0.000000e+00,0.000000,0.000000,0.000000,1.000000e+00
FLAG_DOCUMENT_14,307511.0,0.002936,0.054110,0.000000e+00,0.000000,0.000000,0.000000,1.000000e+00
FLAG_DOCUMENT_15,307511.0,0.001210,0.034760,0.000000e+00,0.000000,0.000000,0.000000,1.000000e+00
FLAG_DOCUMENT_16,307511.0,0.009928,0.099144,0.000000e+00,0.000000,0.000000,0.000000,1.000000e+00
FLAG_DOCUMENT_17,307511.0,0.000267,0.016327,0.000000e+00,0.000000,0.000000,0.000000,1.000000e+00
FLAG_DOCUMENT_18,307511.0,0.008130,0.089798,0.000000e+00,0.000000,0.000000,0.000000,1.000000e+00
FLAG_DOCUMENT_19,307511.0,0.000595,0.024387,0.000000e+00,0.000000,0.000000,0.000000,1.000000e+00
FLAG_DOCUMENT_20,307511.0,0.000507,0.022518,0.000000e+00,0.000000,0.000000,0.000000,1.000000e+00
FLAG_DOCUMENT_21,307511.0,0.000335,0.018299,0.000000e+00,0.000000,0.000000,0.000000,1.000000e+00
AMT_REQ_CREDIT_BUREAU_HOUR,265992.0,0.006402,0.083849,0.000000e+00,0.000000,0.000000,0.000000,4.000000e+00
AMT_REQ_CREDIT_BUREAU_DAY,265992.0,0.007000,0.110757,0.000000e+00,0.000000,0.000000,0.000000,9.000000e+00
AMT_REQ_CREDIT_BUREAU_WEEK,265992.0,0.034362,0.204685,0.000000e+00,0.000000,0.000000,0.000000,8.000000e+00
AMT_REQ_CREDIT_BUREAU_MON,265992.0,0.267395,0.916002,0.000000e+00,0.000000,0.000000,0.000000,2.700000e+01
AMT_REQ_CREDIT_BUREAU_QRT,265992.0,0.265474,0.794056,0.000000e+00,0.000000,0.000000,0.000000,2.610000e+02
AMT_REQ_CREDIT_BUREAU_YEAR,265992.0,1.899974,1.869295,0.000000e+00,0.000000,1.000000,3.000000,2.500000e+01

# SUMMARY

1. we have 307511 row and  122 columns

2. 41 columns in dataset are having more than 50% of nan values

3. 8% are the people with payment issue

4. Almost all columns have less standard deviation which means low variance means nearer to mean

5. The data seem to be disbalanced with respect to target variable

if the standard deviation is high that means your data have high variance. And if you compare the mean and 50% percentile (median) you can see the skewness of your numeric variables. From skewness you can infer that your numeric variables have too many outlier or not.


standard deviation----->variance

mean,mode---->skewness

sknewness--->outliers


positively skewed:   mean of the data is greater than the median 

mean=median= mode symmetrical distribution

negatively skewed: mean is less than median


we find skewness of data so that we can transform data in (normal distribution)

In [ ]:
df["NAME_CONTRACT_TYPE"].value_counts()

Cash loans         278232
Revolving loans     29279
Name: NAME_CONTRACT_TYPE, dtype: int64

we have 36935 client with cash loan and 3847 with revolving loans

In [ ]:
df["TARGET"].value_counts()

0    282686
1     24825
Name: TARGET, dtype: int64

In [ ]:
3299/len(df)*100

1.0728071516140885

8% i.e 3299 in the records have payment issue

In [ ]:
df["CODE_GENDER"].value_counts()

F      202448
M      105059
XNA         4
Name: CODE_GENDER, dtype: int64

We have 2:1 ratio in our records for F:M

In [ ]:
df_info=df[["AMT_INCOME_TOTAL","AMT_CREDIT"]]
df_info["times"]=np.floor(df["AMT_CREDIT"]/df["AMT_INCOME_TOTAL"])
df_info.head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

   AMT_INCOME_TOTAL  AMT_CREDIT  times
0          202500.0    406597.5    2.0
1          270000.0   1293502.5    4.0
2           67500.0    135000.0    2.0
3          135000.0    312682.5    2.0
4          121500.0    513000.0    4.0

In [ ]:
#Education based defaluters
df[df["TARGET"]==1]["NAME_EDUCATION_TYPE"].value_counts()

Secondary / secondary special    19524
Higher education                  4009
Incomplete higher                  872
Lower secondary                    417
Academic degree                      3
Name: NAME_EDUCATION_TYPE, dtype: int64

In [ ]:
#Income type defaluters
df[df["TARGET"]==1]["NAME_INCOME_TYPE"].value_counts()

Working                 15224
Commercial associate     5360
Pensioner                2982
State servant            1249
Unemployed                  8
Maternity leave             2
Name: NAME_INCOME_TYPE, dtype: int64

# Summary



**To see the distribution of contract type**     

      Contract type       Frequency
      Cash loans           36935
      Revolving loans      3847


**8% i.e 3299 in the records have payment issue**

**female to male ratio is 2:1**

F:      202448

M:      105059

**To see income and credit ratio**

	AMT_INCOME_TOTAL	AMT_CREDIT	times

	202500.0	        406597.5	   2.0

	270000.0	        1293502.5	   4.0

	67500.0	          135000.0	   2.0

	135000.0	        312682.5	   2.0

	121500.0	        513000.0	   4.0



**Education based defaluters**

Secondary / secondary special    19524

Higher education                  4009

Incomplete higher                  872

Lower secondary                    417

Academic degree                      3


**Income type defaluters**

Working                 15224

Commercial associate     5360

Pensioner                2982

State servant            1249

Unemployed                  8

Maternity leave             2

In [ ]:
#Dividing the columns into continuous and discreate column
#threshold =30
cont_col=[]
dis_col=[]
for column in df.columns:
  if len(df[column].unique())>30:
    cont_col.append(column)
  else:
    dis_col.append(column)

#removing the target variable from dis_col
dis_col.remove("TARGET")

In [ ]:
print(f"No of continuous columns:{len(cont_col)} \n No. of discrete columns {len(dis_col)}")

No of continuous columns:58
 No. of discrete columns 63

In [ ]:
df_p=pd.read_csv("/content/gdrive/MyDrive/Colab Notebooks/previous_application.csv")
df_p.head(5)

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,FLAG_LAST_APPL_PER_CONTRACT,NFLAG_LAST_APPL_IN_DAY,RATE_DOWN_PAYMENT,RATE_INTEREST_PRIMARY,RATE_INTEREST_PRIVILEGED,NAME_CASH_LOAN_PURPOSE,NAME_CONTRACT_STATUS,DAYS_DECISION,NAME_PAYMENT_TYPE,CODE_REJECT_REASON,NAME_TYPE_SUITE,NAME_CLIENT_TYPE,NAME_GOODS_CATEGORY,NAME_PORTFOLIO,NAME_PRODUCT_TYPE,CHANNEL_TYPE,SELLERPLACE_AREA,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
0,2030495,271877,Consumer loans,1730.430,17145.0,17145.0,0.0,17145.0,SATURDAY,15,Y,1,0.0,0.182832,0.867336,XAP,Approved,-73,Cash through the bank,XAP,NaN,Repeater,Mobile,POS,XNA,Country-wide,35,Connectivity,12.0,middle,POS mobile with interest,365243.0,-42.0,300.0,-42.0,-37.0,0.0
1,2802425,108129,Cash loans,25188.615,607500.0,679671.0,NaN,607500.0,THURSDAY,11,Y,1,NaN,NaN,NaN,XNA,Approved,-164,XNA,XAP,Unaccompanied,Repeater,XNA,Cash,x-sell,Contact center,-1,XNA,36.0,low_action,Cash X-Sell: low,365243.0,-134.0,916.0,365243.0,365243.0,1.0
2,2523466,122040,Cash loans,15060.735,112500.0,136444.5,NaN,112500.0,TUESDAY,11,Y,1,NaN,NaN,NaN,XNA,Approved,-301,Cash through the bank,XAP,"Spouse, partner",Repeater,XNA,Cash,x-sell,Credit and cash offices,-1,XNA,12.0,high,Cash X-Sell: high,365243.0,-271.0,59.0,365243.0,365243.0,1.0
3,2819243,176158,Cash loans,47041.335,450000.0,470790.0,NaN,450000.0,MONDAY,7,Y,1,NaN,NaN,NaN,XNA,Approved,-512,Cash through the bank,XAP,NaN,Repeater,XNA,Cash,x-sell,Credit and cash offices,-1,XNA,12.0,middle,Cash X-Sell: middle,365243.0,-482.0,-152.0,-182.0,-177.0,1.0
4,1784265,202054,Cash loans,31924.395,337500.0,404055.0,NaN,337500.0,THURSDAY,9,Y,1,NaN,NaN,NaN,Repairs,Refused,-781,Cash through the bank,HC,NaN,Repeater,XNA,Cash,walk-in,Credit and cash offices,-1,XNA,24.0,high,Cash Street: high,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
print(f"No of rows and columns are:{df_p.shape}" )

No of rows and columns are:(1670214, 37)

In [ ]:
print("Getting information about column\n\n", df_p.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1670214 entries, 0 to 1670213
Data columns (total 37 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   SK_ID_PREV                   1670214 non-null  int64
 1   SK_ID_CURR                   1670214 non-null  int64
 2   NAME_CONTRACT_TYPE           1670214 non-null  object
 3   AMT_ANNUITY                  1297979 non-null  float64
 4   AMT_APPLICATION              1670214 non-null  float64
 5   AMT_CREDIT                   1670213 non-null  float64
 6   AMT_DOWN_PAYMENT             774370 non-null   float64
 7   AMT_GOODS_PRICE              1284699 non-null  float64
 8   WEEKDAY_APPR_PROCESS_START   1670214 non-null  object
 9   HOUR_APPR_PROCESS_START      1670214 non-null  int64
 10  FLAG_LAST_APPL_PER_CONTRACT  1670214 non-null  object
 11  NFLAG_LAST_APPL_IN_DAY       1670214 non-null  int64
 12  RATE_DOWN_PAYMENT            774370 non-null   float64
 13  RATE_INTEREST_PRIMARY        5951 non-null     float64
 14  RATE_INTEREST_PRIVILEGED     5951 non-null     float64
 15  NAME_CASH_LOAN_PURPOSE       1670214 non-null  object
 16  NAME_CONTRACT_STATUS         1670214 non-null  object
 17  DAYS_DECISION                1670214 non-null  int64
 18  NAME_PAYMENT_TYPE            1670214 non-null  object
 19  CODE_REJECT_REASON           1670214 non-null  object
 20  NAME_TYPE_SUITE              849809 non-null   object
 21  NAME_CLIENT_TYPE             1670214 non-null  object
 22  NAME_GOODS_CATEGORY          1670214 non-null  object
 23  NAME_PORTFOLIO               1670214 non-null  object
 24  NAME_PRODUCT_TYPE            1670214 non-null  object
 25  CHANNEL_TYPE                 1670214 non-null  object
 26  SELLERPLACE_AREA             1670214 non-null  int64
 27  NAME_SELLER_INDUSTRY         1670214 non-null  object
 28  CNT_PAYMENT                  1297984 non-null  float64
 29  NAME_YIELD_GROUP             1670214 non-null  object
 30  PRODUCT_COMBINATION          1669868 non-null  object
 31  DAYS_FIRST_DRAWING           997149 non-null   float64
 32  DAYS_FIRST_DUE               997149 non-null   float64
 33  DAYS_LAST_DUE_1ST_VERSION    997149 non-null   float64
 34  DAYS_LAST_DUE                997149 non-null   float64
 35  DAYS_TERMINATION             997149 non-null   float64
 36  NFLAG_INSURED_ON_APPROVAL    997149 non-null   float64
dtypes: float64(15), int64(6), object(16)
memory usage: 471.5+ MB
Getting information about column

 None

In [ ]:
print("Getting name of all columns: \n\n",df_p.columns)

Getting name of all columns:

 Index(['SK_ID_PREV', 'SK_ID_CURR', 'NAME_CONTRACT_TYPE', 'AMT_ANNUITY',
       'AMT_APPLICATION', 'AMT_CREDIT', 'AMT_DOWN_PAYMENT', 'AMT_GOODS_PRICE',
       'WEEKDAY_APPR_PROCESS_START', 'HOUR_APPR_PROCESS_START',
       'FLAG_LAST_APPL_PER_CONTRACT', 'NFLAG_LAST_APPL_IN_DAY',
       'RATE_DOWN_PAYMENT', 'RATE_INTEREST_PRIMARY',
       'RATE_INTEREST_PRIVILEGED', 'NAME_CASH_LOAN_PURPOSE',
       'NAME_CONTRACT_STATUS', 'DAYS_DECISION', 'NAME_PAYMENT_TYPE',
       'CODE_REJECT_REASON', 'NAME_TYPE_SUITE', 'NAME_CLIENT_TYPE',
       'NAME_GOODS_CATEGORY', 'NAME_PORTFOLIO', 'NAME_PRODUCT_TYPE',
       'CHANNEL_TYPE', 'SELLERPLACE_AREA', 'NAME_SELLER_INDUSTRY',
       'CNT_PAYMENT', 'NAME_YIELD_GROUP', 'PRODUCT_COMBINATION',
       'DAYS_FIRST_DRAWING', 'DAYS_FIRST_DUE', 'DAYS_LAST_DUE_1ST_VERSION',
       'DAYS_LAST_DUE', 'DAYS_TERMINATION', 'NFLAG_INSURED_ON_APPROVAL'],
      dtype='object')

In [ ]:
df_p.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
SK_ID_PREV,1670214.0,1.923089e+06,532597.958696,1.000001e+06,1.461857e+06,1.923110e+06,2.384280e+06,2845382.000
SK_ID_CURR,1670214.0,2.783572e+05,102814.823849,1.000010e+05,1.893290e+05,2.787145e+05,3.675140e+05,456255.000
AMT_ANNUITY,1297979.0,1.595512e+04,14782.137335,0.000000e+00,6.321780e+03,1.125000e+04,2.065842e+04,418058.145
AMT_APPLICATION,1670214.0,1.752339e+05,292779.762387,0.000000e+00,1.872000e+04,7.104600e+04,1.803600e+05,6905160.000
AMT_CREDIT,1670213.0,1.961140e+05,318574.616546,0.000000e+00,2.416050e+04,8.054100e+04,2.164185e+05,6905160.000
AMT_DOWN_PAYMENT,774370.0,6.697402e+03,20921.495410,-9.000000e-01,0.000000e+00,1.638000e+03,7.740000e+03,3060045.000
AMT_GOODS_PRICE,1284699.0,2.278473e+05,315396.557937,0.000000e+00,5.084100e+04,1.123200e+05,2.340000e+05,6905160.000
HOUR_APPR_PROCESS_START,1670214.0,1.248418e+01,3.334028,0.000000e+00,1.000000e+01,1.200000e+01,1.500000e+01,23.000
NFLAG_LAST_APPL_IN_DAY,1670214.0,9.964675e-01,0.059330,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000
RATE_DOWN_PAYMENT,774370.0,7.963682e-02,0.107823,-1.497876e-05,0.000000e+00,5.160508e-02,1.089091e-01,1.000
RATE_INTEREST_PRIMARY,5951.0,1.883569e-01,0.087671,3.478125e-02,1.607163e-01,1.891222e-01,1.933299e-01,1.000
RATE_INTEREST_PRIVILEGED,5951.0,7.735025e-01,0.100879,3.731501e-01,7.156448e-01,8.350951e-01,8.525370e-01,1.000
DAYS_DECISION,1670214.0,-8.806797e+02,779.099667,-2.922000e+03,-1.300000e+03,-5.810000e+02,-2.800000e+02,-1.000
SELLERPLACE_AREA,1670214.0,3.139511e+02,7127.443459,-1.000000e+00,-1.000000e+00,3.000000e+00,8.200000e+01,4000000.000
CNT_PAYMENT,1297984.0,1.605408e+01,14.567288,0.000000e+00,6.000000e+00,1.200000e+01,2.400000e+01,84.000
DAYS_FIRST_DRAWING,997149.0,3.422099e+05,88916.115834,-2.922000e+03,3.652430e+05,3.652430e+05,3.652430e+05,365243.000
DAYS_FIRST_DUE,997149.0,1.382627e+04,72444.869708,-2.892000e+03,-1.628000e+03,-8.310000e+02,-4.110000e+02,365243.000
DAYS_LAST_DUE_1ST_VERSION,997149.0,3.376777e+04,106857.034789,-2.801000e+03,-1.242000e+03,-3.610000e+02,1.290000e+02,365243.000
DAYS_LAST_DUE,997149.0,7.658240e+04,149647.415123,-2.889000e+03,-1.314000e+03,-5.370000e+02,-7.400000e+01,365243.000
DAYS_TERMINATION,997149.0,8.199234e+04,153303.516729,-2.874000e+03,-1.270000e+03,-4.990000e+02,-4.400000e+01,365243.000
NFLAG_INSURED_ON_APPROVAL,997149.0,3.325702e-01,0.471134,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.000

In [ ]:
(df_p.isna().sum()/len(df_p)*100).sort_values()

SK_ID_PREV                      0.000000
NAME_YIELD_GROUP                0.000000
NAME_SELLER_INDUSTRY            0.000000
SELLERPLACE_AREA                0.000000
CHANNEL_TYPE                    0.000000
NAME_PRODUCT_TYPE               0.000000
NAME_PORTFOLIO                  0.000000
NAME_GOODS_CATEGORY             0.000000
NAME_CLIENT_TYPE                0.000000
CODE_REJECT_REASON              0.000000
DAYS_DECISION                   0.000000
NAME_CONTRACT_STATUS            0.000000
NAME_CASH_LOAN_PURPOSE          0.000000
NAME_PAYMENT_TYPE               0.000000
AMT_APPLICATION                 0.000000
NFLAG_LAST_APPL_IN_DAY          0.000000
FLAG_LAST_APPL_PER_CONTRACT     0.000000
HOUR_APPR_PROCESS_START         0.000000
WEEKDAY_APPR_PROCESS_START      0.000000
NAME_CONTRACT_TYPE              0.000000
SK_ID_CURR                      0.000000
AMT_CREDIT                      0.000060
PRODUCT_COMBINATION             0.020716
CNT_PAYMENT                    22.286366
AMT_ANNUITY                    22.286665
AMT_GOODS_PRICE                23.081773
DAYS_LAST_DUE                  40.298129
DAYS_LAST_DUE_1ST_VERSION      40.298129
DAYS_FIRST_DUE                 40.298129
DAYS_FIRST_DRAWING             40.298129
NFLAG_INSURED_ON_APPROVAL      40.298129
DAYS_TERMINATION               40.298129
NAME_TYPE_SUITE                49.119754
AMT_DOWN_PAYMENT               53.636480
RATE_DOWN_PAYMENT              53.636480
RATE_INTEREST_PRIMARY          99.643698
RATE_INTEREST_PRIVILEGED       99.643698
dtype: float64

In [ ]:
#correlation between df(application) and df_p(previous application)
col_app=list(df.columns)
col_prev=list(df_p.columns)
uni_col=[]
[uni_col.append(col) for col  in col_app if col not in uni_col]
[uni_col.append(col) for col in col_prev if col not in col_app]

uni_col=list(set(uni_col))
    
print(f"List of columns unique in application.csv and previous application")

List of columns unique in application.csv and previous application

In [ ]:
#common columns
common=[]
[common.append(col) for col in col_app if col in col_prev]
common

['SK_ID_CURR',
 'NAME_CONTRACT_TYPE',
 'AMT_CREDIT',
 'AMT_ANNUITY',
 'AMT_GOODS_PRICE',
 'NAME_TYPE_SUITE',
 'WEEKDAY_APPR_PROCESS_START',
 'HOUR_APPR_PROCESS_START']

In [ ]:
final_df.head(5)

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,COMMONAREA_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,FLOORSMIN_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,FONDKAPREMONT_MODE,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,SK_ID_PREV,AMT_APPLICATION,AMT_DOWN_PAYMENT,FLAG_LAST_APPL_PER_CONTRACT,NFLAG_LAST_APPL_IN_DAY,RATE_DOWN_PAYMENT,RATE_INTEREST_PRIMARY,RATE_INTEREST_PRIVILEGED,NAME_CASH_LOAN_PURPOSE,NAME_CONTRACT_STATUS,DAYS_DECISION,NAME_PAYMENT_TYPE,CODE_REJECT_REASON,NAME_CLIENT_TYPE,NAME_GOODS_CATEGORY,NAME_PORTFOLIO,NAME_PRODUCT_TYPE,CHANNEL_TYPE,SELLERPLACE_AREA,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
0,186234,0,Revolving loans,F,N,Y,0,67500.0,270000.0,13500.0,270000.0,Unaccompanied,Pensioner,Secondary / secondary special,Married,House / apartment,0.035792,-22766,365243,-12271.0,-385,NaN,1,0,0,1,0,0,NaN,2.0,2,2,FRIDAY,11,0,0,0,0,0,0,XNA,NaN,0.767935,0.285180,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-739.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,6.0,1371600,270000.0,NaN,Y,1,NaN,NaN,NaN,XAP,Refused,-294,XNA,HC,Repeater,XNA,Cards,x-sell,Credit and cash offices,-1,XNA,0.0,XNA,Card X-Sell,NaN,NaN,NaN,NaN,NaN,NaN
1,195755,0,Cash loans,F,Y,Y,2,142425.0,450000.0,17140.5,450000.0,Unaccompanied,Commercial associate,Higher education,Married,House / apartment,0.028663,-11392,-3528,-4800.0,-3920,18.0,1,1,1,1,1,0,Managers,4.0,2,2,TUESDAY,10,0,0,0,0,1,1,Other,0.637823,0.529897,0.649620,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-461.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,1.0,0.0,2.0,4.0,1104802,450000.0,NaN,Y,1,NaN,NaN,NaN,XNA,Approved,-28,Cash through the bank,XAP,Repeater,XNA,Cash,x-sell,Channel of corporate sales,-1,XNA,36.0,low_normal,Cash X-Sell: low,NaN,NaN,NaN,NaN,NaN,NaN
2,278454,0,Cash loans,M,Y,N,0,157500.0,900000.0,26316.0,900000.0,Unaccompanied,Pensioner,Higher education,Married,House / apartment,0.008866,-23709,365243,-465.0,-3059,23.0,1,0,0,1,0,0,NaN,2.0,2,2,WEDNESDAY,20,0,0,0,0,0,0,XNA,NaN,0.542427,0.754406,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-1987.0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0,2149551,900000.0,NaN,Y,1,NaN,NaN,NaN,XNA,Approved,-21,XNA,XAP,Repeater,XNA,Cash,x-sell,Contact center,-1,XNA,60.0,low_normal,Cash X-Sell: low,NaN,NaN,NaN,NaN,NaN,NaN
3,312735,0,Revolving loans,F,N,Y,0,202500.0,450000.0,22500.0,450000.0,Unaccompanied,Pensioner,Secondary / secondary special,Widow,House / apartment,0.009630,-20636,365243,-7309.0,-712,NaN,1,0,0,1,0,0,NaN,1.0,2,2,TUESDAY,13,0,0,0,0,0,0,XNA,NaN,0.520229,0.519097,0.0876,0.0458,0.9901,0.864,0.0155,0.0,0.2414,0.1667,0.0417,0.0694,0.0698,0.0881,0.0077,0.0065,0.0893,0.0475,0.9901,0.8693,0.0156,0.0,0.2414,0.1667,0.0417,0.071,0.0762,0.0918,0.0078,0.0069,0.0885,0.0458,0.9901,0.8658,0.0156,0.0,0.2414,0.1667,0.0417,0.0706,0.071,0.0897,0.0078,0.0067,reg oper account,block of flats,0.0792,"Stone, brick",No,6.0,0.0,6.0,0.0,-599.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0,1965328,450000.0,NaN,Y,1,NaN,NaN,NaN,XAP,Refused,-245,XNA,HC,Repeater,XNA,Cards,x-sell,Credit and cash offices,-1,XNA,0.0,XNA,Card X-Sell,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
final_df.shape

(4, 151)

In [ ]:
#Experiment for merging the data
a=df.iloc[:2,:]
b=df_p[df_p["SK_ID_CURR"]==100003]
c=pd.merge(a,b,on="SK_ID_CURR")
display(a,b,c)

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,COMMONAREA_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,FLOORSMIN_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,FONDKAPREMONT_MODE,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,351000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.018801,-9461,-637,-3648.0,-2120,NaN,1,1,0,1,1,0,Laborers,1.0,2,2,WEDNESDAY,10,0,0,0,0,0,0,Business Entity Type 3,0.083037,0.262949,0.139376,0.0247,0.0369,0.9722,0.6192,0.0143,0.00,0.0690,0.0833,0.1250,0.0369,0.0202,0.0190,0.0000,0.0000,0.0252,0.0383,0.9722,0.6341,0.0144,0.0000,0.0690,0.0833,0.1250,0.0377,0.022,0.0198,0.0,0.0,0.0250,0.0369,0.9722,0.6243,0.0144,0.00,0.0690,0.0833,0.1250,0.0375,0.0205,0.0193,0.0000,0.00,reg oper account,block of flats,0.0149,"Stone, brick",No,2.0,2.0,2.0,2.0,-1134.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,1129500.0,Family,State servant,Higher education,Married,House / apartment,0.003541,-16765,-1188,-1186.0,-291,NaN,1,1,0,1,1,0,Core staff,2.0,1,1,MONDAY,11,0,0,0,0,0,0,School,0.311267,0.622246,NaN,0.0959,0.0529,0.9851,0.7960,0.0605,0.08,0.0345,0.2917,0.3333,0.0130,0.0773,0.0549,0.0039,0.0098,0.0924,0.0538,0.9851,0.8040,0.0497,0.0806,0.0345,0.2917,0.3333,0.0128,0.079,0.0554,0.0,0.0,0.0968,0.0529,0.9851,0.7987,0.0608,0.08,0.0345,0.2917,0.3333,0.0132,0.0787,0.0558,0.0039,0.01,reg oper account,block of flats,0.0714,Block,No,1.0,0.0,1.0,0.0,-828.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,FLAG_LAST_APPL_PER_CONTRACT,NFLAG_LAST_APPL_IN_DAY,RATE_DOWN_PAYMENT,RATE_INTEREST_PRIMARY,RATE_INTEREST_PRIVILEGED,NAME_CASH_LOAN_PURPOSE,NAME_CONTRACT_STATUS,DAYS_DECISION,NAME_PAYMENT_TYPE,CODE_REJECT_REASON,NAME_TYPE_SUITE,NAME_CLIENT_TYPE,NAME_GOODS_CATEGORY,NAME_PORTFOLIO,NAME_PRODUCT_TYPE,CHANNEL_TYPE,SELLERPLACE_AREA,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
575941,1810518,100003,Cash loans,98356.995,900000.0,1035882.0,NaN,900000.0,FRIDAY,12,Y,1,NaN,NaN,NaN,XNA,Approved,-746,XNA,XAP,Unaccompanied,Repeater,XNA,Cash,x-sell,Credit and cash offices,-1,XNA,12.0,low_normal,Cash X-Sell: low,365243.0,-716.0,-386.0,-536.0,-527.0,1.0
1021650,2636178,100003,Consumer loans,64567.665,337500.0,348637.5,0.0,337500.0,SUNDAY,17,Y,1,0.000000,NaN,NaN,XAP,Approved,-828,Cash through the bank,XAP,Family,Refreshed,Furniture,POS,XNA,Stone,1400,Furniture,6.0,middle,POS industry with interest,365243.0,-797.0,-647.0,-647.0,-639.0,0.0
1223745,2396755,100003,Consumer loans,6737.310,68809.5,68053.5,6885.0,68809.5,SATURDAY,15,Y,1,0.100061,NaN,NaN,XAP,Approved,-2341,Cash through the bank,XAP,Family,Refreshed,Consumer Electronics,POS,XNA,Country-wide,200,Consumer electronics,12.0,middle,POS household with interest,365243.0,-2310.0,-1980.0,-1980.0,-1976.0,1.0

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE_x,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT_x,AMT_ANNUITY_x,AMT_GOODS_PRICE_x,NAME_TYPE_SUITE_x,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START_x,HOUR_APPR_PROCESS_START_x,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,COMMONAREA_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,FLOORSMIN_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,FONDKAPREMONT_MODE,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,SK_ID_PREV,NAME_CONTRACT_TYPE_y,AMT_ANNUITY_y,AMT_APPLICATION,AMT_CREDIT_y,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE_y,WEEKDAY_APPR_PROCESS_START_y,HOUR_APPR_PROCESS_START_y,FLAG_LAST_APPL_PER_CONTRACT,NFLAG_LAST_APPL_IN_DAY,RATE_DOWN_PAYMENT,RATE_INTEREST_PRIMARY,RATE_INTEREST_PRIVILEGED,NAME_CASH_LOAN_PURPOSE,NAME_CONTRACT_STATUS,DAYS_DECISION,NAME_PAYMENT_TYPE,CODE_REJECT_REASON,NAME_TYPE_SUITE_y,NAME_CLIENT_TYPE,NAME_GOODS_CATEGORY,NAME_PORTFOLIO,NAME_PRODUCT_TYPE,CHANNEL_TYPE,SELLERPLACE_AREA,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
0,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,1129500.0,Family,State servant,Higher education,Married,House / apartment,0.003541,-16765,-1188,-1186.0,-291,NaN,1,1,0,1,1,0,Core staff,2.0,1,1,MONDAY,11,0,0,0,0,0,0,School,0.311267,0.622246,NaN,0.0959,0.0529,0.9851,0.796,0.0605,0.08,0.0345,0.2917,0.3333,0.013,0.0773,0.0549,0.0039,0.0098,0.0924,0.0538,0.9851,0.804,0.0497,0.0806,0.0345,0.2917,0.3333,0.0128,0.079,0.0554,0.0,0.0,0.0968,0.0529,0.9851,0.7987,0.0608,0.08,0.0345,0.2917,0.3333,0.0132,0.0787,0.0558,0.0039,0.01,reg oper account,block of flats,0.0714,Block,No,1.0,0.0,1.0,0.0,-828.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,1810518,Cash loans,98356.995,900000.0,1035882.0,NaN,900000.0,FRIDAY,12,Y,1,NaN,NaN,NaN,XNA,Approved,-746,XNA,XAP,Unaccompanied,Repeater,XNA,Cash,x-sell,Credit and cash offices,-1,XNA,12.0,low_normal,Cash X-Sell: low,365243.0,-716.0,-386.0,-536.0,-527.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,1129500.0,Family,State servant,Higher education,Married,House / apartment,0.003541,-16765,-1188,-1186.0,-291,NaN,1,1,0,1,1,0,Core staff,2.0,1,1,MONDAY,11,0,0,0,0,0,0,School,0.311267,0.622246,NaN,0.0959,0.0529,0.9851,0.796,0.0605,0.08,0.0345,0.2917,0.3333,0.013,0.0773,0.0549,0.0039,0.0098,0.0924,0.0538,0.9851,0.804,0.0497,0.0806,0.0345,0.2917,0.3333,0.0128,0.079,0.0554,0.0,0.0,0.0968,0.0529,0.9851,0.7987,0.0608,0.08,0.0345,0.2917,0.3333,0.0132,0.0787,0.0558,0.0039,0.01,reg oper account,block of flats,0.0714,Block,No,1.0,0.0,1.0,0.0,-828.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,2636178,Consumer loans,64567.665,337500.0,348637.5,0.0,337500.0,SUNDAY,17,Y,1,0.000000,NaN,NaN,XAP,Approved,-828,Cash through the bank,XAP,Family,Refreshed,Furniture,POS,XNA,Stone,1400,Furniture,6.0,middle,POS industry with interest,365243.0,-797.0,-647.0,-647.0,-639.0,0.0
2,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,1129500.0,Family,State servant,Higher education,Married,House / apartment,0.003541,-16765,-1188,-1186.0,-291,NaN,1,1,0,1,1,0,Core staff,2.0,1,1,MONDAY,11,0,0,0,0,0,0,School,0.311267,0.622246,NaN,0.0959,0.0529,0.9851,0.796,0.0605,0.08,0.0345,0.2917,0.3333,0.013,0.0773,0.0549,0.0039,0.0098,0.0924,0.0538,0.9851,0.804,0.0497,0.0806,0.0345,0.2917,0.3333,0.0128,0.079,0.0554,0.0,0.0,0.0968,0.0529,0.9851,0.7987,0.0608,0.08,0.0345,0.2917,0.3333,0.0132,0.0787,0.0558,0.0039,0.01,reg oper account,block of flats,0.0714,Block,No,1.0,0.0,1.0,0.0,-828.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,2396755,Consumer loans,6737.310,68809.5,68053.5,6885.0,68809.5,SATURDAY,15,Y,1,0.100061,NaN,NaN,XAP,Approved,-2341,Cash through the bank,XAP,Family,Refreshed,Consumer Electronics,POS,XNA,Country-wide,200,Consumer electronics,12.0,middle,POS household with interest,365243.0,-2310.0,-1980.0,-1980.0,-1976.0,1.0

In [ ]:
#merging the two dataset
final_df=pd.merge(df, df_p,on='SK_ID_CURR')

In [ ]:
final_df.head()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE_x,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT_x,AMT_ANNUITY_x,AMT_GOODS_PRICE_x,NAME_TYPE_SUITE_x,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START_x,HOUR_APPR_PROCESS_START_x,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,COMMONAREA_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,FLOORSMIN_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,FONDKAPREMONT_MODE,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,SK_ID_PREV,NAME_CONTRACT_TYPE_y,AMT_ANNUITY_y,AMT_APPLICATION,AMT_CREDIT_y,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE_y,WEEKDAY_APPR_PROCESS_START_y,HOUR_APPR_PROCESS_START_y,FLAG_LAST_APPL_PER_CONTRACT,NFLAG_LAST_APPL_IN_DAY,RATE_DOWN_PAYMENT,RATE_INTEREST_PRIMARY,RATE_INTEREST_PRIVILEGED,NAME_CASH_LOAN_PURPOSE,NAME_CONTRACT_STATUS,DAYS_DECISION,NAME_PAYMENT_TYPE,CODE_REJECT_REASON,NAME_TYPE_SUITE_y,NAME_CLIENT_TYPE,NAME_GOODS_CATEGORY,NAME_PORTFOLIO,NAME_PRODUCT_TYPE,CHANNEL_TYPE,SELLERPLACE_AREA,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,351000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.018801,-9461,-637,-3648.0,-2120,NaN,1,1,0,1,1,0,Laborers,1.0,2,2,WEDNESDAY,10,0,0,0,0,0,0,Business Entity Type 3,0.083037,0.262949,0.139376,0.0247,0.0369,0.9722,0.6192,0.0143,0.00,0.0690,0.0833,0.1250,0.0369,0.0202,0.0190,0.0000,0.0000,0.0252,0.0383,0.9722,0.6341,0.0144,0.0000,0.0690,0.0833,0.1250,0.0377,0.022,0.0198,0.0,0.0,0.0250,0.0369,0.9722,0.6243,0.0144,0.00,0.0690,0.0833,0.1250,0.0375,0.0205,0.0193,0.0000,0.00,reg oper account,block of flats,0.0149,"Stone, brick",No,2.0,2.0,2.0,2.0,-1134.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,1038818,Consumer loans,9251.775,179055.0,179055.0,0.0,179055.0,SATURDAY,9,Y,1,0.000000,NaN,NaN,XAP,Approved,-606,XNA,XAP,NaN,New,Vehicles,POS,XNA,Stone,500,Auto technology,24.0,low_normal,POS other with interest,365243.0,-565.0,125.0,-25.0,-17.0,0.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,1129500.0,Family,State servant,Higher education,Married,House / apartment,0.003541,-16765,-1188,-1186.0,-291,NaN,1,1,0,1,1,0,Core staff,2.0,1,1,MONDAY,11,0,0,0,0,0,0,School,0.311267,0.622246,NaN,0.0959,0.0529,0.9851,0.7960,0.0605,0.08,0.0345,0.2917,0.3333,0.0130,0.0773,0.0549,0.0039,0.0098,0.0924,0.0538,0.9851,0.8040,0.0497,0.0806,0.0345,0.2917,0.3333,0.0128,0.079,0.0554,0.0,0.0,0.0968,0.0529,0.9851,0.7987,0.0608,0.08,0.0345,0.2917,0.3333,0.0132,0.0787,0.0558,0.0039,0.01,reg oper account,block of flats,0.0714,Block,No,1.0,0.0,1.0,0.0,-828.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,1810518,Cash loans,98356.995,900000.0,1035882.0,NaN,900000.0,FRIDAY,12,Y,1,NaN,NaN,NaN,XNA,Approved,-746,XNA,XAP,Unaccompanied,Repeater,XNA,Cash,x-sell,Credit and cash offices,-1,XNA,12.0,low_normal,Cash X-Sell: low,365243.0,-716.0,-386.0,-536.0,-527.0,1.0
2,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,1129500.0,Family,State servant,Higher education,Married,House / apartment,0.003541,-16765,-1188,-1186.0,-291,NaN,1,1,0,1,1,0,Core staff,2.0,1,1,MONDAY,11,0,0,0,0,0,0,School,0.311267,0.622246,NaN,0.0959,0.0529,0.9851,0.7960,0.0605,0.08,0.0345,0.2917,0.3333,0.0130,0.0773,0.0549,0.0039,0.0098,0.0924,0.0538,0.9851,0.8040,0.0497,0.0806,0.0345,0.2917,0.3333,0.0128,0.079,0.0554,0.0,0.0,0.0968,0.0529,0.9851,0.7987,0.0608,0.08,0.0345,0.2917,0.3333,0.0132,0.0787,0.0558,0.0039,0.01,reg oper account,block of flats,0.0714,Block,No,1.0,0.0,1.0,0.0,-828.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,2636178,Consumer loans,64567.665,337500.0,348637.5,0.0,337500.0,SUNDAY,17,Y,1,0.000000,NaN,NaN,XAP,Approved,-828,Cash through the bank,XAP,Family,Refreshed,Furniture,POS,XNA,Stone,1400,Furniture,6.0,middle,POS industry with interest,365243.0,-797.0,-647.0,-647.0,-639.0,0.0
3,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,1129500.0,Family,State servant,Higher education,Married,House / apartment,0.003541,-16765,-1188,-1186.0,-291,NaN,1,1,0,1,1,0,Core staff,2.0,1,1,MONDAY,11,0,0,0,0,0,0,School,0.311267,0.622246,NaN,0.0959,0.0529,0.9851,0.7960,0.0605,0.08,0.0345,0.2917,0.3333,0.0130,0.0773,0.0549,0.0039,0.0098,0.0924,0.0538,0.9851,0.8040,0.0497,0.0806,0.0345,0.2917,0.3333,0.0128,0.079,0.0554,0.0,0.0,0.0968,0.0529,0.9851,0.7987,0.0608,0.08,0.0345,0.2917,0.3333,0.0132,0.0787,0.0558,0.0039,0.01,reg oper account,block of flats,0.0714,Block,No,1.0,0.0,1.0,0.0,-828.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,2396755,Consumer loans,6737.310,68809.5,68053.5,6885.0,68809.5,SATURDAY,15,Y,1,0.100061,NaN,NaN,XAP,Approved,-2341,Cash through the bank,XAP,Family,Refreshed,Consumer Electronics,POS,XNA,Country-wide,200,Consumer electronics,12.0,middle,POS household with interest,365243.0,-2310.0,-1980.0,-1980.0,-1976.0,1.0
4,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,135000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.010032,-19046,-225,-4260.0,-2531,26.0,1,1,1,1,1,0,Laborers,1.0,2,2,MONDAY,9,0,0,0,0,0,0,Government,NaN,0.555912,0.729567,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-815.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,1564014,Consumer loans,5357.250,24282.0,20106.0,4860.0,24282.0,FRIDAY,5,Y,1,0.212008,NaN,NaN,XAP,Approved,-815,Cash through the bank,XAP,Unaccompanied,New,Mobile,POS,XNA,Regional / Local,30,Connectivity,4.0,middle,POS mobile without interest,365243.0,-784.0,-694.0,-724.0,-714.0,0.0

In [ ]:
final_df.shape

(1413701, 158)

In [ ]:
lst=list(final_df.columns)

In [ ]:
lst.index("SK_ID_PREV")

122

In [ ]:
col_lst=[]
col_lst.append(lst[122])
col_lst.extend(lst[:122])
col_lst.extend(lst[123:])
col_lst

['SK_ID_PREV',
 'SK_ID_CURR',
 'TARGET',
 'NAME_CONTRACT_TYPE_x',
 'CODE_GENDER',
 'FLAG_OWN_CAR',
 'FLAG_OWN_REALTY',
 'CNT_CHILDREN',
 'AMT_INCOME_TOTAL',
 'AMT_CREDIT_x',
 'AMT_ANNUITY_x',
 'AMT_GOODS_PRICE_x',
 'NAME_TYPE_SUITE_x',
 'NAME_INCOME_TYPE',
 'NAME_EDUCATION_TYPE',
 'NAME_FAMILY_STATUS',
 'NAME_HOUSING_TYPE',
 'REGION_POPULATION_RELATIVE',
 'DAYS_BIRTH',
 'DAYS_EMPLOYED',
 'DAYS_REGISTRATION',
 'DAYS_ID_PUBLISH',
 'OWN_CAR_AGE',
 'FLAG_MOBIL',
 'FLAG_EMP_PHONE',
 'FLAG_WORK_PHONE',
 'FLAG_CONT_MOBILE',
 'FLAG_PHONE',
 'FLAG_EMAIL',
 'OCCUPATION_TYPE',
 'CNT_FAM_MEMBERS',
 'REGION_RATING_CLIENT',
 'REGION_RATING_CLIENT_W_CITY',
 'WEEKDAY_APPR_PROCESS_START_x',
 'HOUR_APPR_PROCESS_START_x',
 'REG_REGION_NOT_LIVE_REGION',
 'REG_REGION_NOT_WORK_REGION',
 'LIVE_REGION_NOT_WORK_REGION',
 'REG_CITY_NOT_LIVE_CITY',
 'REG_CITY_NOT_WORK_CITY',
 'LIVE_CITY_NOT_WORK_CITY',
 'ORGANIZATION_TYPE',
 'EXT_SOURCE_1',
 'EXT_SOURCE_2',
 'EXT_SOURCE_3',
 'APARTMENTS_AVG',
 'BASEMENTAREA_AVG',
 'YEARS_BEGINEXPLUATATION_AVG',
 'YEARS_BUILD_AVG',
 'COMMONAREA_AVG',
 'ELEVATORS_AVG',
 'ENTRANCES_AVG',
 'FLOORSMAX_AVG',
 'FLOORSMIN_AVG',
 'LANDAREA_AVG',
 'LIVINGAPARTMENTS_AVG',
 'LIVINGAREA_AVG',
 'NONLIVINGAPARTMENTS_AVG',
 'NONLIVINGAREA_AVG',
 'APARTMENTS_MODE',
 'BASEMENTAREA_MODE',
 'YEARS_BEGINEXPLUATATION_MODE',
 'YEARS_BUILD_MODE',
 'COMMONAREA_MODE',
 'ELEVATORS_MODE',
 'ENTRANCES_MODE',
 'FLOORSMAX_MODE',
 'FLOORSMIN_MODE',
 'LANDAREA_MODE',
 'LIVINGAPARTMENTS_MODE',
 'LIVINGAREA_MODE',
 'NONLIVINGAPARTMENTS_MODE',
 'NONLIVINGAREA_MODE',
 'APARTMENTS_MEDI',
 'BASEMENTAREA_MEDI',
 'YEARS_BEGINEXPLUATATION_MEDI',
 'YEARS_BUILD_MEDI',
 'COMMONAREA_MEDI',
 'ELEVATORS_MEDI',
 'ENTRANCES_MEDI',
 'FLOORSMAX_MEDI',
 'FLOORSMIN_MEDI',
 'LANDAREA_MEDI',
 'LIVINGAPARTMENTS_MEDI',
 'LIVINGAREA_MEDI',
 'NONLIVINGAPARTMENTS_MEDI',
 'NONLIVINGAREA_MEDI',
 'FONDKAPREMONT_MODE',
 'HOUSETYPE_MODE',
 'TOTALAREA_MODE',
 'WALLSMATERIAL_MODE',
 'EMERGENCYSTATE_MODE',
 'OBS_30_CNT_SOCIAL_CIRCLE',
 'DEF_30_CNT_SOCIAL_CIRCLE',
 'OBS_60_CNT_SOCIAL_CIRCLE',
 'DEF_60_CNT_SOCIAL_CIRCLE',
 'DAYS_LAST_PHONE_CHANGE',
 'FLAG_DOCUMENT_2',
 'FLAG_DOCUMENT_3',
 'FLAG_DOCUMENT_4',
 'FLAG_DOCUMENT_5',
 'FLAG_DOCUMENT_6',
 'FLAG_DOCUMENT_7',
 'FLAG_DOCUMENT_8',
 'FLAG_DOCUMENT_9',
 'FLAG_DOCUMENT_10',
 'FLAG_DOCUMENT_11',
 'FLAG_DOCUMENT_12',
 'FLAG_DOCUMENT_13',
 'FLAG_DOCUMENT_14',
 'FLAG_DOCUMENT_15',
 'FLAG_DOCUMENT_16',
 'FLAG_DOCUMENT_17',
 'FLAG_DOCUMENT_18',
 'FLAG_DOCUMENT_19',
 'FLAG_DOCUMENT_20',
 'FLAG_DOCUMENT_21',
 'AMT_REQ_CREDIT_BUREAU_HOUR',
 'AMT_REQ_CREDIT_BUREAU_DAY',
 'AMT_REQ_CREDIT_BUREAU_WEEK',
 'AMT_REQ_CREDIT_BUREAU_MON',
 'AMT_REQ_CREDIT_BUREAU_QRT',
 'AMT_REQ_CREDIT_BUREAU_YEAR',
 'NAME_CONTRACT_TYPE_y',
 'AMT_ANNUITY_y',
 'AMT_APPLICATION',
 'AMT_CREDIT_y',
 'AMT_DOWN_PAYMENT',
 'AMT_GOODS_PRICE_y',
 'WEEKDAY_APPR_PROCESS_START_y',
 'HOUR_APPR_PROCESS_START_y',
 'FLAG_LAST_APPL_PER_CONTRACT',
 'NFLAG_LAST_APPL_IN_DAY',
 'RATE_DOWN_PAYMENT',
 'RATE_INTEREST_PRIMARY',
 'RATE_INTEREST_PRIVILEGED',
 'NAME_CASH_LOAN_PURPOSE',
 'NAME_CONTRACT_STATUS',
 'DAYS_DECISION',
 'NAME_PAYMENT_TYPE',
 'CODE_REJECT_REASON',
 'NAME_TYPE_SUITE_y',
 'NAME_CLIENT_TYPE',
 'NAME_GOODS_CATEGORY',
 'NAME_PORTFOLIO',
 'NAME_PRODUCT_TYPE',
 'CHANNEL_TYPE',
 'SELLERPLACE_AREA',
 'NAME_SELLER_INDUSTRY',
 'CNT_PAYMENT',
 'NAME_YIELD_GROUP',
 'PRODUCT_COMBINATION',
 'DAYS_FIRST_DRAWING',
 'DAYS_FIRST_DUE',
 'DAYS_LAST_DUE_1ST_VERSION',
 'DAYS_LAST_DUE',
 'DAYS_TERMINATION',
 'NFLAG_INSURED_ON_APPROVAL']

In [ ]:
df=final_df[col_lst]
df.head()

,SK_ID_PREV,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE_x,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT_x,AMT_ANNUITY_x,AMT_GOODS_PRICE_x,NAME_TYPE_SUITE_x,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START_x,HOUR_APPR_PROCESS_START_x,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,COMMONAREA_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,FLOORSMIN_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,FONDKAPREMONT_MODE,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,NAME_CONTRACT_TYPE_y,AMT_ANNUITY_y,AMT_APPLICATION,AMT_CREDIT_y,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE_y,WEEKDAY_APPR_PROCESS_START_y,HOUR_APPR_PROCESS_START_y,FLAG_LAST_APPL_PER_CONTRACT,NFLAG_LAST_APPL_IN_DAY,RATE_DOWN_PAYMENT,RATE_INTEREST_PRIMARY,RATE_INTEREST_PRIVILEGED,NAME_CASH_LOAN_PURPOSE,NAME_CONTRACT_STATUS,DAYS_DECISION,NAME_PAYMENT_TYPE,CODE_REJECT_REASON,NAME_TYPE_SUITE_y,NAME_CLIENT_TYPE,NAME_GOODS_CATEGORY,NAME_PORTFOLIO,NAME_PRODUCT_TYPE,CHANNEL_TYPE,SELLERPLACE_AREA,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
0,1038818,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,351000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.018801,-9461,-637,-3648.0,-2120,NaN,1,1,0,1,1,0,Laborers,1.0,2,2,WEDNESDAY,10,0,0,0,0,0,0,Business Entity Type 3,0.083037,0.262949,0.139376,0.0247,0.0369,0.9722,0.6192,0.0143,0.00,0.0690,0.0833,0.1250,0.0369,0.0202,0.0190,0.0000,0.0000,0.0252,0.0383,0.9722,0.6341,0.0144,0.0000,0.0690,0.0833,0.1250,0.0377,0.022,0.0198,0.0,0.0,0.0250,0.0369,0.9722,0.6243,0.0144,0.00,0.0690,0.0833,0.1250,0.0375,0.0205,0.0193,0.0000,0.00,reg oper account,block of flats,0.0149,"Stone, brick",No,2.0,2.0,2.0,2.0,-1134.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,Consumer loans,9251.775,179055.0,179055.0,0.0,179055.0,SATURDAY,9,Y,1,0.000000,NaN,NaN,XAP,Approved,-606,XNA,XAP,NaN,New,Vehicles,POS,XNA,Stone,500,Auto technology,24.0,low_normal,POS other with interest,365243.0,-565.0,125.0,-25.0,-17.0,0.0
1,1810518,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,1129500.0,Family,State servant,Higher education,Married,House / apartment,0.003541,-16765,-1188,-1186.0,-291,NaN,1,1,0,1,1,0,Core staff,2.0,1,1,MONDAY,11,0,0,0,0,0,0,School,0.311267,0.622246,NaN,0.0959,0.0529,0.9851,0.7960,0.0605,0.08,0.0345,0.2917,0.3333,0.0130,0.0773,0.0549,0.0039,0.0098,0.0924,0.0538,0.9851,0.8040,0.0497,0.0806,0.0345,0.2917,0.3333,0.0128,0.079,0.0554,0.0,0.0,0.0968,0.0529,0.9851,0.7987,0.0608,0.08,0.0345,0.2917,0.3333,0.0132,0.0787,0.0558,0.0039,0.01,reg oper account,block of flats,0.0714,Block,No,1.0,0.0,1.0,0.0,-828.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,Cash loans,98356.995,900000.0,1035882.0,NaN,900000.0,FRIDAY,12,Y,1,NaN,NaN,NaN,XNA,Approved,-746,XNA,XAP,Unaccompanied,Repeater,XNA,Cash,x-sell,Credit and cash offices,-1,XNA,12.0,low_normal,Cash X-Sell: low,365243.0,-716.0,-386.0,-536.0,-527.0,1.0
2,2636178,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,1129500.0,Family,State servant,Higher education,Married,House / apartment,0.003541,-16765,-1188,-1186.0,-291,NaN,1,1,0,1,1,0,Core staff,2.0,1,1,MONDAY,11,0,0,0,0,0,0,School,0.311267,0.622246,NaN,0.0959,0.0529,0.9851,0.7960,0.0605,0.08,0.0345,0.2917,0.3333,0.0130,0.0773,0.0549,0.0039,0.0098,0.0924,0.0538,0.9851,0.8040,0.0497,0.0806,0.0345,0.2917,0.3333,0.0128,0.079,0.0554,0.0,0.0,0.0968,0.0529,0.9851,0.7987,0.0608,0.08,0.0345,0.2917,0.3333,0.0132,0.0787,0.0558,0.0039,0.01,reg oper account,block of flats,0.0714,Block,No,1.0,0.0,1.0,0.0,-828.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,Consumer loans,64567.665,337500.0,348637.5,0.0,337500.0,SUNDAY,17,Y,1,0.000000,NaN,NaN,XAP,Approved,-828,Cash through the bank,XAP,Family,Refreshed,Furniture,POS,XNA,Stone,1400,Furniture,6.0,middle,POS industry with interest,365243.0,-797.0,-647.0,-647.0,-639.0,0.0
3,2396755,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,1129500.0,Family,State servant,Higher education,Married,House / apartment,0.003541,-16765,-1188,-1186.0,-291,NaN,1,1,0,1,1,0,Core staff,2.0,1,1,MONDAY,11,0,0,0,0,0,0,School,0.311267,0.622246,NaN,0.0959,0.0529,0.9851,0.7960,0.0605,0.08,0.0345,0.2917,0.3333,0.0130,0.0773,0.0549,0.0039,0.0098,0.0924,0.0538,0.9851,0.8040,0.0497,0.0806,0.0345,0.2917,0.3333,0.0128,0.079,0.0554,0.0,0.0,0.0968,0.0529,0.9851,0.7987,0.0608,0.08,0.0345,0.2917,0.3333,0.0132,0.0787,0.0558,0.0039,0.01,reg oper account,block of flats,0.0714,Block,No,1.0,0.0,1.0,0.0,-828.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,Consumer loans,6737.310,68809.5,68053.5,6885.0,68809.5,SATURDAY,15,Y,1,0.100061,NaN,NaN,XAP,Approved,-2341,Cash through the bank,XAP,Family,Refreshed,Consumer Electronics,POS,XNA,Country-wide,200,Consumer electronics,12.0,middle,POS household with interest,365243.0,-2310.0,-1980.0,-1980.0,-1976.0,1.0
4,1564014,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,135000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.010032,-19046,-225,-4260.0,-2531,26.0,1,1,1,1,1,0,Laborers,1.0,2,2,MONDAY,9,0,0,0,0,0,0,Government,NaN,0.555912,0.729567,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-815.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,Consumer loans,5357.250,24282.0,20106.0,4860.0,24282.0,FRIDAY,5,Y,1,0.212008,NaN,NaN,XAP,Approved,-815,Cash through the bank,XAP,Unaccompanied,New,Mobile,POS,XNA,Regional / Local,30,Connectivity,4.0,middle,POS mobile without interest,365243.0,-784.0,-694.0,-724.0,-714.0,0.0

In [ ]:
df.shape

(1413701, 158)

We have 1413701 rows and 158 columns after merging the data from application.csv and prev_application.

In [ ]:
df["TARGET"].value_counts()

0    1291341
1     122360
Name: TARGET, dtype: int64

The dataset seems to be disbalanced with respective to target variable.

In [ ]:
#columns with more than 50% nan values
print("columns with more than 50 % of nan values")
nans=((df.isna().sum()/len(df))*100).sort_values()
print("count: ",nans[nans.values>50].count())
nans[nans.values>50]

columns with more than 50 % of nan values
count:  38

APARTMENTS_MODE             50.364115
APARTMENTS_AVG              50.364115
APARTMENTS_MEDI             50.364115
WALLSMATERIAL_MODE          50.462297
ELEVATORS_AVG               52.996779
ELEVATORS_MODE              52.996779
ELEVATORS_MEDI              52.996779
AMT_DOWN_PAYMENT            53.019698
RATE_DOWN_PAYMENT           53.019698
NONLIVINGAREA_AVG           54.860115
NONLIVINGAREA_MEDI          54.860115
NONLIVINGAREA_MODE          54.860115
EXT_SOURCE_1                56.366870
BASEMENTAREA_AVG            58.308511
BASEMENTAREA_MEDI           58.308511
BASEMENTAREA_MODE           58.308511
LANDAREA_MEDI               59.218533
LANDAREA_MODE               59.218533
LANDAREA_AVG                59.218533
OWN_CAR_AGE                 66.294499
YEARS_BUILD_MODE            66.298107
YEARS_BUILD_AVG             66.298107
YEARS_BUILD_MEDI            66.298107
FLOORSMIN_AVG               67.670604
FLOORSMIN_MODE              67.670604
FLOORSMIN_MEDI              67.670604
LIVINGAPARTMENTS_MEDI       68.214566
LIVINGAPARTMENTS_MODE       68.214566
LIVINGAPARTMENTS_AVG        68.214566
FONDKAPREMONT_MODE          68.216264
NONLIVINGAPARTMENTS_AVG     69.296549
NONLIVINGAPARTMENTS_MEDI    69.296549
NONLIVINGAPARTMENTS_MODE    69.296549
COMMONAREA_AVG              69.689347
COMMONAREA_MODE             69.689347
COMMONAREA_MEDI             69.689347
RATE_INTEREST_PRIVILEGED    99.661102
RATE_INTEREST_PRIMARY       99.661102
dtype: float64


38 columns with  more than 50%  nan values are dependent on each other in which Rate_interest_Privileged and Rate_interest_Primay with 99% nan value

In [ ]:
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
SK_ID_PREV,1413701.0,1.922744e+06,532715.335255,1.000001e+06,1.461346e+06,1.922698e+06,2.384012e+06,2.845381e+06
SK_ID_CURR,1413701.0,2.784813e+05,102811.788043,1.000020e+05,1.893640e+05,2.789920e+05,3.675560e+05,4.562550e+05
TARGET,1413701.0,8.655296e-02,0.281179,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
CNT_CHILDREN,1413701.0,4.048933e-01,0.717345,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.900000e+01
AMT_INCOME_TOTAL,1413701.0,1.733160e+05,198573.372016,2.565000e+04,1.125000e+05,1.575000e+05,2.070000e+05,1.170000e+08
AMT_CREDIT_x,1413701.0,5.875537e+05,384917.331385,4.500000e+04,2.700000e+05,5.084955e+05,8.079840e+05,4.050000e+06
AMT_ANNUITY_x,1413608.0,2.701702e+04,13951.164803,1.615500e+03,1.682100e+04,2.492550e+04,3.454200e+04,2.250000e+05
AMT_GOODS_PRICE_x,1412493.0,5.277186e+05,353246.491860,4.050000e+04,2.385000e+05,4.500000e+05,6.795000e+05,4.050000e+06
REGION_POPULATION_RELATIVE,1413701.0,2.074985e-02,0.013347,2.900000e-04,1.003200e-02,1.885000e-02,2.866300e-02,7.250800e-02
DAYS_BIRTH,1413701.0,-1.632105e+04,4344.557089,-2.520100e+04,-1.998000e+04,-1.604400e+04,-1.273900e+04,-7.489000e+03
DAYS_EMPLOYED,1413701.0,6.870203e+04,145277.704778,-1.791200e+04,-2.828000e+03,-1.281000e+03,-2.840000e+02,3.652430e+05
DAYS_REGISTRATION,1413701.0,-5.003233e+03,3551.050912,-2.467200e+04,-7.510000e+03,-4.508000e+03,-2.001000e+03,0.000000e+00
DAYS_ID_PUBLISH,1413701.0,-3.034563e+03,1507.376375,-7.197000e+03,-4.319000e+03,-3.330000e+03,-1.783000e+03,0.000000e+00
OWN_CAR_AGE,476495.0,1.201195e+01,12.067141,0.000000e+00,5.000000e+00,9.000000e+00,1.500000e+01,9.100000e+01
FLAG_MOBIL,1413701.0,1.000000e+00,0.000000,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
FLAG_EMP_PHONE,1413701.0,8.064393e-01,0.395089,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
FLAG_WORK_PHONE,1413701.0,1.822585e-01,0.386058,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
FLAG_CONT_MOBILE,1413701.0,9.992452e-01,0.027462,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
FLAG_PHONE,1413701.0,2.828752e-01,0.450396,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00
FLAG_EMAIL,1413701.0,7.242904e-02,0.259197,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
CNT_FAM_MEMBERS,1413701.0,2.150501e+00,0.900679,1.000000e+00,2.000000e+00,2.000000e+00,3.000000e+00,2.000000e+01
REGION_RATING_CLIENT,1413701.0,2.059638e+00,0.495780,1.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,3.000000e+00
REGION_RATING_CLIENT_W_CITY,1413701.0,2.037603e+00,0.488643,1.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,3.000000e+00
HOUR_APPR_PROCESS_START_x,1413701.0,1.198433e+01,3.232181,0.000000e+00,1.000000e+01,1.200000e+01,1.400000e+01,2.300000e+01
REG_REGION_NOT_LIVE_REGION,1413701.0,1.207327e-02,0.109213,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
REG_REGION_NOT_WORK_REGION,1413701.0,4.396686e-02,0.205021,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
LIVE_REGION_NOT_WORK_REGION,1413701.0,3.604793e-02,0.186410,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
REG_CITY_NOT_LIVE_CITY,1413701.0,7.360538e-02,0.261128,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
REG_CITY_NOT_WORK_CITY,1413701.0,2.221481e-01,0.415690,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
LIVE_CITY_NOT_WORK_CITY,1413701.0,1.740601e-01,0.379161,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
EXT_SOURCE_1,616842.0,5.054990e-01,0.210748,1.456813e-02,3.385549e-01,5.101381e-01,6.784983e-01,9.626928e-01
EXT_SOURCE_2,1411880.0,5.114275e-01,0.191119,8.173617e-08,3.890839e-01,5.627679e-01,6.606783e-01,8.549997e-01
EXT_SOURCE_3,1171859.0,4.896986e-01,0.196536,5.272652e-04,3.441550e-01,5.100895e-01,6.479769e-01,8.960095e-01
APARTMENTS_AVG,701703.0,1.149783e-01,0.104870,0.000000e+00,5.670000e-02,8.560000e-02,1.474000e-01,1.000000e+00
BASEMENTAREA_AVG,589393.0,8.698938e-02,0.080745,0.000000e+00,4.340000e-02,7.540000e-02,1.109000e-01,1.000000e+00
YEARS_BEGINEXPLUATATION_AVG,729019.0,9.772352e-01,0.061647,0.000000e+00,9.767000e-01,9.816000e-01,9.866000e-01,1.000000e+00
YEARS_BUILD_AVG,476444.0,7.496433e-01,0.113048,0.000000e+00,6.872000e-01,7.552000e-01,8.164000e-01,1.000000e+00
COMMONAREA_AVG,428502.0,4.340559e-02,0.073492,0.000000e+00,7.800000e-03,2.080000e-02,5.050000e-02,1.000000e+00
ELEVATORS_AVG,664485.0,7.525023e-02,0.130434,0.000000e+00,0.000000e+00,0.000000e+00,1.200000e-01,1.000000e+00
ENTRANCES_AVG,706919.0,1.487248e-01,0.099005,0.000000e+00,6.900000e-02,1.379000e-01,2.069000e-01,1.000000e+00
FLOORSMAX_AVG,715193.0,2.223169e-01,0.140943,0.000000e+00,1.667000e-01,1.667000e-01,3.333000e-01,1.000000e+00
FLOORSMIN_AVG,457041.0,2.287916e-01,0.158112,0.000000e+00,8.330000e-02,2.083000e-01,3.750000e-01,1.000000e+00
LANDAREA_AVG,576528.0,6.561416e-02,0.079438,0.000000e+00,1.920000e-02,4.810000e-02,8.470000e-02,1.000000e+00
LIVINGAPARTMENTS_AVG,449351.0,9.886160e-02,0.090477,0.000000e+00,5.040000e-02,7.480000e-02,1.210000e-01,1.000000e+00
LIVINGAREA_AVG,709301.0,1.047002e-01,0.107025,0.000000e+00,4.480000e-02,7.290000e-02,1.252000e-01,1.000000e+00
NONLIVINGAPARTMENTS_AVG,434055.0,8.608387e-03,0.047742,0.000000e+00,0.000000e+00,0.000000e+00,3.900000e-03,1.000000e+00
NONLIVINGAREA_AVG,638143.0,2.747308e-02,0.067045,0.000000e+00,0.000000e+00,3.400000e-03,2.690000e-02,1.000000e+00
APARTMENTS_MODE,701703.0,1.120754e-01,0.104846,0.000000e+00,5.150000e-02,8.400000e-02,1.408000e-01,1.000000e+00
BASEMENTAREA_MODE,589393.0,8.627123e-02,0.082634,0.000000e+00,4.010000e-02,7.370000e-02,1.112000e-01,1.000000e+00
YEARS_BEGINEXPLUATATION_MODE,729019.0,9.765155e-01,0.067386,0.000000e+00,9.762000e-01,9.816000e-01,9.866000e-01,1.000000e+00
YEARS_BUILD_MODE,476444.0,7.570512e-01,0.109991,0.000000e+00,6.929000e-01,7.583000e-01,8.236000e-01,1.000000e+00
COMMONAREA_MODE,428502.0,4.153704e-02,0.072112,0.000000e+00,7.200000e-03,1.890000e-02,4.830000e-02,1.000000e+00
ELEVATORS_MODE,664485.0,7.115661e-02,0.128482,0.000000e+00,0.000000e+00,0.000000e+00,1.208000e-01,1.000000e+00
ENTRANCES_MODE,706919.0,1.444221e-01,0.099944,0.000000e+00,6.900000e-02,1.379000e-01,2.069000e-01,1.000000e+00
FLOORSMAX_MODE,715193.0,2.185555e-01,0.140270,0.000000e+00,1.667000e-01,1.667000e-01,3.333000e-01,1.000000e+00
FLOORSMIN_MODE,457041.0,2.251441e-01,0.158063,0.000000e+00,8.330000e-02,2.083000e-01,3.750000e-01,1.000000e+00
LANDAREA_MODE,576528.0,6.443580e-02,0.080475,0.000000e+00,1.710000e-02,4.590000e-02,8.330000e-02,1.000000e+00
LIVINGAPARTMENTS_MODE,449351.0,1.037555e-01,0.095260,0.000000e+00,5.330000e-02,7.440000e-02,1.304000e-01,1.000000e+00
LIVINGAREA_MODE,709301.0,1.035499e-01,0.108344,0.000000e+00,4.230000e-02,7.240000e-02,1.223000e-01,1.000000e+00
NONLIVINGAPARTMENTS_MODE,434055.0,7.909267e-03,0.046166,0.000000e+00,0.000000e+00,0.000000e+00,3.900000e-03,1.000000e+00
NONLIVINGAREA_MODE,638143.0,2.622994e-02,0.067934,0.000000e+00,0.000000e+00,9.000000e-04,2.280000e-02,1.000000e+00
APARTMENTS_MEDI,701703.0,1.154101e-01,0.105692,0.000000e+00,5.730000e-02,8.430000e-02,1.478000e-01,1.000000e+00
BASEMENTAREA_MEDI,589393.0,8.655118e-02,0.080593,0.000000e+00,4.290000e-02,7.490000e-02,1.103000e-01,1.000000e+00
YEARS_BEGINEXPLUATATION_MEDI,729019.0,9.772196e-01,0.062588,0.000000e+00,9.767000e-01,9.816000e-01,9.866000e-01,1.000000e+00
YEARS_BUILD_MEDI,476444.0,7.529891e-01,0.111880,0.000000e+00,6.914000e-01,7.585000e-01,8.189000e-01,1.000000e+00
COMMONAREA_MEDI,428502.0,4.339609e-02,0.073533,0.000000e+00,7.800000e-03,2.060000e-02,5.040000e-02,1.000000e+00
ELEVATORS_MEDI,664485.0,7.446049e-02,0.130349,0.000000e+00,0.000000e+00,0.000000e+00,1.200000e-01,1.000000e+00
ENTRANCES_MEDI,706919.0,1.482547e-01,0.099315,0.000000e+00,6.900000e-02,1.379000e-01,2.069000e-01,1.000000e+00
FLOORSMAX_MEDI,715193.0,2.219452e-01,0.141436,0.000000e+00,1.667000e-01,1.667000e-01,3.333000e-01,1.000000e+00
FLOORSMIN_MEDI,457041.0,2.285432e-01,0.158747,0.000000e+00,8.330000e-02,2.083000e-01,3.750000e-01,1.000000e+00
LANDAREA_MEDI,576528.0,6.648836e-02,0.080525,0.000000e+00,1.930000e-02,4.870000e-02,8.590000e-02,1.000000e+00
LIVINGAPARTMENTS_MEDI,449351.0,1.000279e-01,0.091411,0.000000e+00,5.130000e-02,7.520000e-02,1.231000e-01,1.000000e+00
LIVINGAREA_MEDI,709301.0,1.058876e-01,0.108645,0.000000e+00,4.510000e-02,7.360000e-02,1.258000e-01,1.000000e+00
NONLIVINGAPARTMENTS_MEDI,434055.0,8.484604e-03,0.047601,0.000000e+00,0.000000e+00,0.000000e+00,3.900000e-03,1.000000e+00
NONLIVINGAREA_MEDI,638143.0,2.737504e-02,0.067623,0.000000e+00,0.000000e+00,2.900000e-03,2.610000e-02,1.000000e+00
TOTALAREA_MODE,736160.0,9.992154e-02,0.103888,0.000000e+00,4.080000e-02,6.800000e-02,1.227000e-01,1.000000e+00
OBS_30_CNT_SOCIAL_CIRCLE,1410555.0,1.544176e+00,2.530715,0.000000e+00,0.000000e+00,0.000000e+00,2.000000e+00,3.480000e+02
DEF_30_CNT_SOCIAL_CIRCLE,1410555.0,1.540436e-01,0.465897,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.400000e+01
OBS_60_CNT_SOCIAL_CIRCLE,1410555.0,1.526303e+00,2.508953,0.000000e+00,0.000000e+00,0.000000e+00,2.000000e+00,3.440000e+02
DEF_60_CNT_SOCIAL_CIRCLE,1410555.0,1.080426e-01,0.379059,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.400000e+01
DAYS_LAST_PHONE_CHANGE,1413701.0,-1.084701e+03,799.936851,-4.292000e+03,-1.683000e+03,-1.011000e+03,-3.960000e+02,0.000000e+00
FLAG_DOCUMENT_2,1413701.0,7.073632e-05,0.008410,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
FLAG_DOCUMENT_3,1413701.0,7.385600e-01,0.439419,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
FLAG_DOCUMENT_4,1413701.0,7.639522e-05,0.008740,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
FLAG_DOCUMENT_5,1413701.0,1.369597e-02,0.116226,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
FLAG_DOCUMENT_6,1413701.0,8.942273e-02,0.285353,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
FLAG_DOCUMENT_7,1413701.0,2.129163e-04,0.014590,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
FLAG_DOCUMENT_8,1413701.0,7.442521e-02,0.262462,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
FLAG_DOCUMENT_9,1413701.0,3.182427e-03,0.056323,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
FLAG_DOCUMENT_10,1413701.0,5.588169e-05,0.007475,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
FLAG_DOCUMENT_11,1413701.0,1.702623e-03,0.041228,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
FLAG_DOCUMENT_12,1413701.0,1.414726e-06,0.001189,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
FLAG_DOCUMENT_13,1413701.0,1.783970e-03,0.042199,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
FLAG_DOCUMENT_14,1413701.0,1.428874e-03,0.037773,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
FLAG_DOCUMENT_15,1413701.0,6.571404e-04,0.025626,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
FLAG_DOCUMENT_16,1413701.0,6.006221e-03,0.077267,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
FLAG_DOCUMENT_17,1413701.0,1.421800e-04,0.011923,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
FLAG_DOCUMENT_18,1413701.0,4.196078e-03,0.064641,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
FLAG_DOCUMENT_19,1413701.0,3.989528e-04,0.019970,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
FLAG_DOCUMENT_20,1413701.0,3.671215e-04,0.019157,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
FLAG_DOCUMENT_21,1413701.0,2.242341e-04,0.014973,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
AMT_REQ_CREDIT_BUREAU_HOUR,1250074.0,6.202833e-03,0.081885,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.000000e+00
AMT_REQ_CREDIT_BUREAU_DAY,1250074.0,6.817196e-03,0.106527,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,9.000000e+00
AMT_REQ_CREDIT_BUREAU_WEEK,1250074.0,3.856572e-02,0.213657,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,8.000000e+00
AMT_REQ_CREDIT_BUREAU_MON,1250074.0,3.013734e-01,0.980290,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.700000e+01
AMT_REQ_CREDIT_BUREAU_QRT,1250074.0,3.615394e-01,0.925714,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.610000e+02
AMT_REQ_CREDIT_BUREAU_YEAR,1250074.0,2.912612e+00,2.199798,0.000000e+00,1.000000e+00,3.000000e+00,4.000000e+00,2.500000e+01
AMT_ANNUITY_y,1106483.0,1.583718e+04,14724.906897,0.000000e+00,6.257858e+03,1.122376e+04,2.042078e+04,4.180581e+05
AMT_APPLICATION,1413701.0,1.752436e+05,293622.193141,0.000000e+00,1.975050e+04,7.087050e+04,1.800000e+05,5.850000e+06
AMT_CREDIT_y,1413700.0,1.963541e+05,319481.250716,0.000000e+00,2.488050e+04,8.059500e+04,2.156400e+05,4.509688e+06
AMT_DOWN_PAYMENT,664161.0,6.655317e+03,20620.300440,-9.000000e-01,0.000000e+00,1.791000e+03,7.695000e+03,3.060045e+06
AMT_GOODS_PRICE_y,1094176.0,2.264512e+05,315937.604200,0.000000e+00,4.982850e+04,1.102455e+05,2.295000e+05,5.850000e+06
HOUR_APPR_PROCESS_START_y,1413701.0,1.247893e+01,3.331474,0.000000e+00,1.000000e+01,1.200000e+01,1.500000e+01,2.300000e+01
NFLAG_LAST_APPL_IN_DAY,1413701.0,9.964321e-01,0.059626,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
RATE_DOWN_PAYMENT,664161.0,8.017486e-02,0.107784,-1.497876e-05,0.000000e+00,6.248933e-02,1.089118e-01,1.000000e+00
RATE_INTEREST_PRIMARY,4791.0,1.894359e-01,0.090849,3.478125e-02,1.607163e-01,1.891363e-01,1.933299e-01,1.000000e+00
RATE_INTEREST_PRIVILEGED,4791.0,7.712840e-01,0.100644,3.731501e-01,7.156448e-01,8.350951e-01,8.525370e-01,1.000000e+00
DAYS_DECISION,1413701.0,-8.803670e+02,783.540171,-2.922000e+03,-1.313000e+03,-5.820000e+02,-2.710000e+02,-1.000000e+00
SELLERPLACE_AREA,1413701.0,3.149878e+02,7695.081664,-1.000000e+00,-1.000000e+00,4.000000e+00,8.500000e+01,4.000000e+06
CNT_PAYMENT,1106488.0,1.605194e+01,14.566746,0.000000e+00,6.000000e+00,1.200000e+01,2.400000e+01,8.400000e+01
DAYS_FIRST_DRAWING,852595.0,3.422577e+05,88832.266598,-2.922000e+03,3.652430e+05,3.652430e+05,3.652430e+05,3.652430e+05
DAYS_FIRST_DUE,852595.0,1.348874e+04,71650.147146,-2.892000e+03,-1.630000e+03,-8.250000e+02,-4.080000e+02,3.652430e+05
DAYS_LAST_DUE_1ST_VERSION,852595.0,3.327483e+04,106161.775933,-2.801000e+03,-1.244000e+03,-3.580000e+02,1.350000e+02,3.652430e+05
DAYS_LAST_DUE,852595.0,7.666563e+04,149704.716371,-2.889000e+03,-1.316000e+03,-5.340000e+02,-7.300000e+01,3.652430e+05
DAYS_TERMINATION,852595.0,8.235317e+04,153537.064274,-2.874000e+03,-1.269000e+03,-4.940000e+02,-4.200000e+01,3.652430e+05
NFLAG_INSURED_ON_APPROVAL,852595.0,3.305720e-01,0.470419,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00

In [ ]:
#columns which are similar with 2 dataset after merging
import re 
for column in df.columns:
  if re.search(".*_x$",str(column))!=None:
    print(re.search(".*_x$",str(column)).group())

NAME_CONTRACT_TYPE_x
AMT_CREDIT_x
AMT_ANNUITY_x
AMT_GOODS_PRICE_x
NAME_TYPE_SUITE_x
WEEKDAY_APPR_PROCESS_START_x
HOUR_APPR_PROCESS_START_x

# **SUMMARY**

1. We have 1413701 rows and 158 columns after merging the data from application.csv and prev_application.


2. 38 columns with  more than 50%  nan values are dependent on each other in which Rate_interest_Privileged and Rate_interest_Primay with 99% nan value 

3. We have 8% of defaulter i.e with payment issue according to the target variable.

4. In most of the cases we have low standard deviation which will tell us less variance  and values closer to mean which is good for classification

5. The dataset seems to be disbalanced with respective to target variable (92% 8% split.)

6. positively skewed data in most of our columns

7. Columns which are similar after merging
  
  NAME_CONTRACT_TYPE_x
  
  AMT_CREDIT_x

  AMT_ANNUITY_x

  AMT_GOODS_PRICE_x

  NAME_TYPE_SUITE_x

  WEEKDAY_APPR_PROCESS_START_x

  HOUR_APPR_PROCESS_START_x

Create hypothesis if required.


id   preid

1    4,5,8